### ISSUE TITLE
Wordpress Oauth plugin/settings to use PDOauth

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#10]
There should be a WordPress plugin which is able to use PDOauth.
To ensure that our implementation is standards compliand, it would be good if we could see that it works with an existing plugin.

**Comment by Claymanus** [comment]
repo is here: https://github.com/edemo/wp_oauth_plugin

**Comment by Claymanus** [comment]
The pludin is ready for demo, further functions and enhancement are under development. See issues in plugin repository.
