### ISSUE TITLE
nem lehet deregisztrálni

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#1001]
hiába jön email, rákattintva üres oldalra jutunk

**Comment by Claymanus** [comment]
emailt másold be ide lécci, de legfőképp a linket, amire kattintottál

**Comment by krosza** [comment]
info@adatom.hu
16:23 (23 hours ago)
to szabo.karoly
Kedves szabo.karoly@noba.hu!

Ezt a levelet azért kaptad mert az ADA oldalán kezdeményezted a
regisztrációd megszüntetését az ADA rendszerében és ezzel együtt valamennyi
adatod törlését az ADA rendszerből. Amennyiben nem te kezdeményezted a
regisztrációd megszüntetését akkor hagyd figyelmen kívül ezt a levelet.

Amennyiben az alábbi linkre kattintasz, akkor az ADA rendszeréből
valamennyi adatod törlésre kerül és az ADA felhasználói fiókod is
megszűnik. Elveszik valamennyi, az ADA rendszerében meglévő igazolásod,
beleértve a személyes tanúsítás során megszerzett igazolásokat is. Azokat a
webes szolgáltatásokat és mobil applikációkat, melyeket az ADA rendszerének
használatával értél el többé már nem fogod tudni elérni.

Itt tudod megerősíteni a regisztrációd megszűntetését:
<https://adatom.hu/fiokom.html?section=deregistration&secret=e10f8a4c269349f8beafd635d2827111>

A link eddig az időpontig érvényes:
10 Jul 2017 14:23:07.

Üdvözlettel:
Az ADA csapata

**Comment by Claymanus** [comment]
javítottam a linket a config.py-ban -> deregistration.html
@krosza teszteld le plíz

**Comment by krosza** [comment]
a helyzet javult, feljön a kijelentkezős oldal de ott hiába kattintok,
megerősítem stb
nem töröl a rendszerből
https://adatom.hu/deregistration.html?secret=60cebaee519d4e85bb65e663a8f5c2
be

ez a levél
info@adatom.hu
17:46 (0 minutes ago)
to vbszk
Kedves vbszk@adatom.hu!

Ezt a levelet azért kaptad mert az ADA oldalán kezdeményezted a
regisztrációd megszüntetését az ADA rendszerében és ezzel együtt valamennyi
adatod törlését az ADA rendszerből. Amennyiben nem te kezdeményezted a
regisztrációd megszüntetését akkor hagyd figyelmen kívül ezt a levelet.

Amennyiben az alábbi linkre kattintasz, akkor az ADA rendszeréből
valamennyi adatod törlésre kerül és az ADA felhasználói fiókod is
megszűnik. Elveszik valamennyi, az ADA rendszerében meglévő igazolásod,
beleértve a személyes tanúsítás során megszerzett igazolásokat is. Azokat a
webes szolgáltatásokat és mobil applikációkat, melyeket az ADA rendszerének
használatával értél el többé már nem fogod tudni elérni.

Itt tudod megerősíteni a regisztrációd megszűntetését:
<https://adatom.hu/deregistration.html?secret=60cebaee519d4e85bb65e663a8f5c2be>

A link eddig az időpontig érvényes:
11 Jul 2017 15:46:48.

Üdvözlettel:
Az ADA csapata

**Comment by Claymanus** [comment]
javítva
