### ISSUE TITLE
email cím megerősítés levél szöveg javítása

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#1010]

**Comment by krosza** [comment]
Erre kellene javítani: ( link elhelyezés változtatás  és a safari szöveg ki)


Kedves         !

Erre a i linkre kattintva:      kattintandó link

    érvényesíted a regisztrációdat az Anonim Digitális Azonosító (ADA) rendszerében és
    elfogadod az ADA Felhasználási Feltételeit és a Közösségi Digitális Eszközök Alapítvány Adatkezelési Tájékoztatóját.

Abban az esetben, ha regisztrációdat egy ADA rendszert használó applikáción keresztül kezdeményezted és a linkre kattintva valamilyen okból nem az adott applikáció oldalára irányítana vissza látogass el újra az applikáció oldalára


A linket a következő időpontig használhatod fel:
13 Jul 2017 05:24:25

Üdvözlettel:
Az ADA csapata

**Comment by Claymanus** [comment]
done

**Comment by krosza** [comment]
akkor tudom letesztelni, ha   @magwas  megjavította a fiók törlést, az összes email címemet elhasználtam már de nem tudom őket törölni

**Comment by Claymanus** [comment]
fiók törlés javítva
