### ISSUE TITLE
Assurance irányító testület felépítése

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#110]

**Comment by Claymanus** [comment]
https://e.demokracia.rulez.org/redmine/projects/assurance/wiki/Assurance_ir%C3%A1ny%C3%ADt%C3%B3_test%C3%BClet_fel%C3%A9p%C3%ADt%C3%A9se

**Comment by krosza** [comment]
Ez meg nincs kesz

**Comment by krosza** [comment]
Elso valtozatot a gdrive on talaljatok.
