### ISSUE TITLE
esetleg lehetne területre vonatkozó információ a user adatrekordjában

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#113]
El kellene gondolkoznunk azon, hogy esetleg a user irányítószámát is nyilvántartsuk.
Akár bele is lehetne drótozni a hashbe. Ez mondjuk  többletfeladatot róna az assurerekre, mert minden költözéskor megváltozna a hash, ergo újra kell a usert assurálni

**Comment by magwas** [comment]
Olyan infó alapján kell csinálni a hash-t, ami
- sosem változik
- egyértelmű, hogy hogyan kell leírni
Az irányítószám nem felel meg az első feltételnek.

**Comment by Claymanus** [comment]
oks
És az ellen van valami érv, hogy az irányítószám is rögzítve legyen, és az is assurált adat legyen?
Persze azon kívül, hogy nem akarunk személyes adatokat tárolni.

**Comment by magwas** [comment]
Az, hogy nem akarunk személyes adatokat tárolni, pont elegendő érv.
Az egy másik dolog, hogy az _assurerekhez_ tárolhatnánk lokációt. A legszebb az lenne, hogy az openstreetmapen ki tudná jelölni az assurer (egy vagy több poligonnal), hogy mely területeken hajlandó assurálni. Openlayers-el megoldható. http://gis.stackexchange.com/questions/27377/openlayers-how-to-create-a-rectangle
