### ISSUE TITLE
elfelejtett jelszó

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#119]
Jó lenne ha lenne rá lehetőség a login oldalon

**Comment by Claymanus** [comment]
https://github.com/Claymanus/PDOauth/commit/88dc6e18771ab07ecd69e5fe38177d640c6ae297

**Comment by krosza** [comment]
Kb mennyi idő múlva kerül ki egy javítás az élő rendszerbe? Pontosabban mikor látni a login oldalon?

**Comment by Claymanus** [comment]
Akkor megy élesbe, ha minden teszt lefutott. Addig itt tudsz játszani vele: https://mi-18.no-ip.biz
