### ISSUE TITLE
egy személyi szám több user id

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#120]
nem probléma hogy egy személyi szám hoz több user ID kapcsolódhat? simán tudok FB reggel és normál reggel ua-a hash-el létezni a rendszerben
 A szavazások esetén ezért ez nem lenne jó

**Comment by Claymanus** [comment]
elvielg nem, mert a megadott hash az assurance által lesz valid. Magát a hasht az alkalmazások nem kapják meg, csak az assurance-t.
így aztán nem is tudom, hogy volna-e értelme definiálhatunk egy "incidens" eseményt, ha két  assurálatlan user hash-e megegyezik. Problémák ott tudnak kezdődni, ha mindkét user assurált, vagyis egy ellenőrzésnél olyan hasht akarunk validálni, amelyik már egy másik validált userhez tartozik. Ugye a dilemma itt a rendszer részéről az, hogy melyik asurernek higgyek.

**Comment by krosza** [comment]
Egyelőre  nagyon alacsony a  várható  assurance % , addig az alkalmazások eléggé hekkelhetőek lesznek, nem beszélve az újságírókról akik örömmel jelentik hogy rossz a rendszer. Az nem megoldható hogy a z SSO szerver ezt figyelje? az első tíz karakternél már biztos kibukik az azonosság. ezért kb ua. mint az email figyelés?

**Comment by Claymanus** [comment]
semmi akadálya, hogy a rendszer figyelje, csak értelme nincs. Mert ez nem fogja megakadályzni abban a rendszert hekkelőkek, hogy több fiókot csináljanak maguknak. Egy emberhez tartozó több fiók ellen csak az assurálás véd.
Amúgy mi legyen az "incidens" következménye? Adjunk mindkét usernek egy "fake" assurancot? Ezzel adott esetben egy valódi usert is (akár rosszindulatúan) ki lehet zár(at)ni. Vagy értesítsük a usereket az ütközésről és pusholjuk őket, hogy kérjenek assurert?

**Comment by krosza** [comment]
következményként  a javaslat:
az elsőnek aki a rendszerben van
- ha van assurance-a akkor  email, hogy vki megpróbált regelni a személyi számával  ...
- ha nincs neki assurance-a email, hogy tegye azt mielőbb meg  
a másodiknak aki épp regisztrál vagy megadja a szem számát email, hogy ütközés van  és jelentse kérjen vitát itt és itt 
de addig ne engedjük hogy legyen titkos kódja

ha nem jön vita indítás akkor ne csináljunk ezen túl semmit, ha jön  akkor a hunyó kizárása...

a hekkelés ellen azt hiszem  igazán csak az védene ha a hashbe beraknánk még egy-két személyes azonosítot...

**Comment by Claymanus** [comment]
nem tudhatod, hogy az első vagy a második a fake, úgyhogy ha a másodikat kizárod, az nem túl szerencsés...

**Comment by krosza** [comment]
jó megoldás nincs azt hiszem,
a második akkor indíthat vitát, és vleg fog, ha ő az igazi és ezt gyorsan rövidre lehet zárni egy assurálással

**Comment by Claymanus** [comment]
Tehát akkor szerinted is a megoldás az érintettek értesítése után az assurálás ;-) Én nem gondolom, hogy ütközés esetén az egyiknek vagy a másiknak több jogot kellene biztosíson a rendszer. Az alkalmazások szempontjából minden user mindaddig fake, amíg nincs assurálva. Az alkalmazások nem kapják meg azt az infót, hogy van-e hash-e a usernek vagy nincs.

**Comment by magwas** [comment]
A jelenlegi megoldás a #5 hibajegyben van dokumentálva.
Ez biztosítja azt, hogy ne legyen egyszerre két hitelesített felhasználó ugyanazzal a hash-el.
A hitelesítetlen felhasználóknál pedig nem gondolom hogy érdekes a kérdés, hiszen a hitelesítésnéleldől, hogy ki az igazi.
Az alacsony belépési küszöb érdekében így hagynám. Gondoljunk arra a use case-tre, amikor valaki regisztrál, elfelejti az accountja adatait és ismét regisztrál. Felesleges az ilyeneket külön szopatni.
