### ISSUE TITLE
digital signature for users - needed for signing assurance certificates

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#129]

**Comment by magwas** [comment]
If the customer creates a certificate credential, she will have the necessary keys.
However using browser certificates for anything other than logging in is at least system dependent and mostly nontrivial.
What would be the use case?

**Comment by Claymanus** [comment]
I mean pdf certificate: assurer and user can sign with their own digital signature the certificate printed into pdf about the assurance event. This pdf can be used as a tracking docs for the user. ( instead of the printed paper base document we discussed )

**Comment by magwas** [comment]
The signer would be another application.
