### ISSUE TITLE
Ellenőrzés

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#149]
Egyelőre csak a teszt miatt van, hogy az ellenőrnek a user vmennyi adata megjelenik? pl az ügyfél pw-t nem kellene látni az ellenőrnek, nem?

**Comment by Claymanus** [comment]
Alapértelmezés szerint az ellenőr csak az assurance-okat láthatja. Nyilván most azért jelenik meg más adat is, hogy lássuk a működést, később kiszedjük, és csak a superuserek láthatnak minden adatot. Persze a jelszavakat még ők sem.

Nekem van egy olyan mániám hogy az assurance-okat is csak akkor láthassa az assurer, ha az assurálási folyamat odáig jutott, hogy a user hozzájárult az assurálásához. Ezt a folyamatot majd még dumáljuk át, itt van valami kezdemény: #115
