### ISSUE TITLE
add callback ability for /keygen calls

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#156]
after keygen need to:
- registration tab: refreshing UI because the user is logged in
- account tab: refreshing credential types in tab

**Comment by magwas** [comment]
Maybe already done, please check

**Comment by magwas** [comment]
can we close this?

**Comment by Claymanus** [comment]
felőlem. Ugye ez akkor fog tudni megoldódni véglegesen, ha kidobjuk a <keygen> tagot a html-ből és átállunk ajaxos certbeszerzésre
