### ISSUE TITLE
email input mező hossza

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#159]
jó lenne ha az ügy fél  ellenőrzés részen az email input mező hosszabb lenne 5-10 karakterrel és látná egyben a felhasználó az egészet

**Comment by Claymanus** [comment]
ok.
csak az assurerek ne nézegessék a useradatokat, ennek a fícsörnek az admin oldalon lenne a helye

**Comment by Claymanus** [comment]
new direction has been defined in #176
