### ISSUE TITLE
ellenőrzés folyamata

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#160]
az ügyfél emailcím megadását követően a mutasd gomb megnyomása után a Fiókom oldalra kerülünk, ahol figyelmeztetés jelenik meg  hogy a hash csere stb ...
gondolom itt egy új lapra kellene a rendszernek ugrania, ahol csak a szem.szám input mező van

azt nem tudtam így kipróbálni működik -e a többi rész
mindenesetre a tanúsítvány kiadása  jó lenne ha 2 lépcsős lenne vagyis felugrana egy megreősítést kérő gomb is

**Comment by Claymanus** [comment]
A UI ezen részét majd értelemszerűen át kell alakítsuk, ha már sikerült definiálni a tanusítás folyamatát.

Azt szeretném javasolni, hogy az assurálásra használjuk inkább a tanusítás, az assurance-ra a tanusítvány szavakat.

**Comment by krosza** [comment]
éa akkor az ellenőrzés helyett is a tanúsítást gondolod?

**Comment by Claymanus** [comment]
igen, nekem az ellenőrzés túl erős, dehonesztáló. A tanusítás meg inkább valami pozitív, elismerő ugyanakkor komolyabb dolog.

**Comment by magwas** [comment]
this - or better should be implemented in the new UI, according tothe assurance handbook. We need the UX design for it.
