### ISSUE TITLE
dokumentáció tervezetek

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#163]
A gdrive.-on lévő dokuban csináltam első tervezeteket, ezekből

Assurance irányító testület felépítése ,  működése , jogosítványai
Kézikönyv ellenőröknek
Vita rendezési folyamat- és ügy 

a wikik (github, redmine) nagyon szétszedik a formatálást ezért inkább javaslom a gdriv-on  szerkesszük ezeket. egyelőre,
 a kék színű részeket ne nézzétek azok még ...
a szóhasználat elég összevissza van egyelőre, azt majd egységesítem ha nagyjából egyetértés van a szövegekkel és megbeszéltük jövő csütörtökön
lsz szóljatok hozzá...

https://docs.google.com/document/d/1ItCOgSbuG9DTGR7v0HeffcYTReBpyKTFM1jp1NU9U9I/edit#heading=h.tq1kroc39hrh

**Comment by Claymanus** [comment]
a redmine és a github wiki [markdown](https://guides.github.com/features/mastering-markdown/) formázást használ,   nem ördöngősség megtanulni. Struktúrált dokumentumrendszerekhez találták ki, nem nyomtatásba kerülő egyedi dokumentumokhoz, mint a google offece szerű cuccai. Én azért gondolom, hogy a wiki style jobb nekünk, mert ezek a doksik nem fognak önálló életet élni, többnyire egy weboldalon nézegetik őket. De elég a véglegesnek szánt változatokat átültetni a wikibe.

**Comment by magwas** [comment]
megbeszéltük,done
