### ISSUE TITLE
pw reset probléma

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#164]
explorer-ben  votl nyitva az SSO, az gmail a firefoxban, kattintás után ezt küldte a rendszer: 
global failure (1, 0, 1)Rerun1 ms

    TypeError: document.getElementById(...) is null@ 1 ms
    Source: 	

    https://sso.edemokraciagep.org/static/script.js:493

global failure (1, 0, 1)Rerun1 ms

    TypeError: document.getElementById(...) is null@ 1 ms
    Source: 	

    https://sso.edemokraciagep.org/static/script.js:184

global failure (1, 0, 1)Rerun1 ms

    TypeError: document.getElementById(...) is null@ 1 ms
    Source: 	

    https://sso.edemokraciagep.org/static/script.js:352

**Comment by Claymanus** [comment]
be voltál jelentkezve?

**Comment by krosza** [comment]
nem mert azzal az account-al nem tudok a régi pw-t nem fogadja, 
megpróbálom egy másikkal

**Comment by Claymanus** [comment]
ok, nálam kijelentkezve hiba nélkül megy, semmi hibát nem dob (IE11.0.20)
bejelentkezve sem dob hibát, csak annak ellenére, hogy aszonta, hogy elküldte a levelet, a levél nem jön meg.
Talán itt nem is kellene ezt a levelezősdit lejátszani...

**Comment by magwas** [comment]
Wontfix: cannot reproduce
