### ISSUE TITLE
registration does not properly changes UI

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#178]
registration also logs in, but this is not reflected in the ui.
this is the reason why the UI is reloaded in src/end2endtest/digest.py, in every test.
See those test to understand the behaviour

**Comment by Claymanus** [comment]
UI will be changed after the user confirms the popup message.
and unfortunately UI is changing too in case of an error appers on the registration tab, but this is an other issue.

**Comment by Claymanus** [comment]
wontfix, UI is changed
