### ISSUE TITLE
automatic list of assurers

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#212]
- assurerek listájának nyilvánossága, hol jelenik meg? Automatikus vagy kézi módszer a rendszerben?
  TODO: automatikus lista
publikus adatok az assurerről:
minimum:
Valódi név
emailcím
Egy téglalap, ami azt a területet jelöli, ahonnan hajlandó assurálni
milyen assurance-okat adhat ki
lehetséges megadni:
telefonszám
rövid szöveg
később: a rendszer tárolja az assurerek személyi igazolvány számát. Az assurálás ideje alatt a “ki assurál éppen” részen megjelenik az assurer összes fenti adata, beleértve a személyi igazolvány számot is a user számára.

A user can choose an assurer from the list and initiate assurance process.

**Comment by Claymanus** [comment]
téglalap helyett legyen inkább egy poligon

**Comment by magwas** [comment]
duplicate of #459
