### ISSUE TITLE
Alapítvány bejegyeztetés

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#239]

**Comment by krosza** [comment]
hiánypótlás lesz:  

fontosabbak: 

csatoljon  igazolást az alapítvány céljára rendelt vagyon rendelkezésre bocsátásáról

ba) pénzbeli vagyonrendelés esetén a pénzforgalmi szolgáltató igazolását a fizetési vagy pénzforgalmi számlán elhelyezett összegről, az ügyvéd vagy a bíróság igazolását az ügyvédi vagy bírósági letétről vagy a közjegyző igazolását az alapítvány céljára rendelt vagyon bizalmi őrzésbe adásáról,

Csatoljon olyan, az alapítvány székhelyének használatát-, annak jogcímét igazoló
okiratot (székhely használati hozzájárulás), amelyben
– a használatot engedélyező személy-szerv adatai között szükséges feltüntetni a nevét,
lakcímét, anyja nevét, születési helyét és idejét,
– a székhelyként felajánlott ingatlan címét, helyrajzi számát,
– az ingatlan tulajdonosainak tulajdoni hányadát,
– a használat jogcímét (pl: szívességi, bérlet).
A nyilatkozatot az ingatlan valamennyi tulajdonosának, az ingatlanon fennálló jog
valamennyi jogosultjának alá kell írni. A nyilatkozatot teljes bizonyító erejű magánokirati
(pl: két tanú) formában kell benyújtani.
(Minta nyilatkozat letölthető a http://birosag.hu/allampolgaroknak/civil-szervezetek internetes
oldalról.)

**Comment by magwas** [comment]
depends #719

**Comment by krosza** [comment]
done

**Comment by krosza** [comment]
még meg kell várnunk, hogy jogerős legyen, mert csak utána kap adószámot
