### ISSUE TITLE
vizsgabiztosok regisztrálása

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#259]

**Comment by magwas** [comment]
ha van vizsgaszabályzat és levizsgáztattuk egymást

**Comment by madcsaba** [comment]
csaba@opengovernment.hu

**Comment by krosza** [comment]
Szabó Károly- ezen regisztráltam: krosza@gmail.com
  ez kellene ide:  vbszk @adatom.hu, és egy ilyen itszk@adatom.hu
