### ISSUE TITLE
static portal

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#261]

**Comment by magwas** [comment]
design megvan, tartalommal kel feltölteni
Ákos javasol, Csaba átnézi, mi megköpködjük.

**Comment by csertanakos** [comment]
![img_1770](https://cloud.githubusercontent.com/assets/9112177/13033519/debe190c-d319-11e5-88cd-30ee5b9d2294.JPG)

**Comment by Claymanus** [comment]
http://patyicivil.hu/ada/index.html
