### ISSUE TITLE
https korrekt certtel a szabadszavazas.hu-ra

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#283]

**Comment by magwas** [comment]
lett új gép neki 91.143.88.153

**Comment by magwas** [comment]
@Claymanus  nézd meg, hogy be tudsz-emenni, és osszuk el, hogy ki mitcsinál meg rajta.

**Comment by magwas** [comment]
nagyjából megvan, de
még a dns-ben át kéne írni.
az apache config valami botrány (a virtualhostokat nem adja ki, egyszerre vagy http vagy https) és nem tudok rájönni, hogy mi baja.
A wordpress is sírogat mindenféléket.
@Claymanus bele tudsz nézni az apache configba, meg a wordpressbe?
@krosza a dns-ről van felvéve külön jegy. amíg az nincs átírva, addig elég nehéz dolgokat csinálni. Egy MX-et is kéne a domainhez. Ha nincs jobb ötlet, akkor legyen ugyanaz,mint a mail.adatom.hu: 91.143.88.149, mail.szabadszavazas.hu néven.

**Comment by krosza** [comment]
mi az az MX,?
 ez is a tárhelyparknál van meg tudom csinálni  és is vagy kérni kell őket

**Comment by Claymanus** [comment]
lol az e.demokracia.rulez.org adatbázisa lett áthozva ;-)
