### ISSUE TITLE
anchorra szöveg

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#286]

**Comment by magwas** [comment]
https://docs.google.com/document/d/1p9aFlRHUo1M4M4k4W_s0hs2ab4JBeiOkxIB1qtHMVEE/edit

**Comment by magwas** [comment]
https://rawgit.com/edemo/PDAnchor/master/index.html

**Comment by krosza** [comment]
https://docs.google.com/document/d/1p9aFlRHUo1M4M4k4W_s0hs2ab4JBeiOkxIB1qtHMVEE/edit

**Comment by Claymanus** [comment]
új skin 
http://patyicivil.hu/wp-content/uploads/index.htm

**Comment by Claymanus** [comment]
szöveg frissítve:
http://patyicivil.hu/wp-content/uploads/index.htm

**Comment by magwas** [comment]
be a kódba!
