### ISSUE TITLE
szabadszavazas.hu dns

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#298]
szabadszavazas.hu új IP címe:
91.143.88.153
át kéne írni a DNS-ben.

**Comment by krosza** [comment]
kértem őket, pár óra általában

**Comment by magwas** [comment]
szóval a következő rekordok kellenének:
@  3600 IN A 91.143.88.153 ; szabadszavazas.hu A
mail 3600 IN A 91.143.88.149 ; mail.szabadszavazas.hu A
@   3600 IN MX mail.szabadszavazas.hu. ; szabadszavazas.hu MX
