### ISSUE TITLE
email szövegek kódolása

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#315]

**Comment by krosza** [comment]
def sendPasswordVerificationEmail(self, user):

"Az alábbi linkre kattintva:
- érvényesíted a regisztrációdat az Anonim Digitális Azonosító (ADA) rendszerében és

- elfogadod az ADA Felhasználási Feltételeit (link) és a Közösségi  Digitális Eszközök 
Alapítvány Adatkezelési Tájékoztatóját.(link)

Abban az esetben, ha regisztrációdat egy ADA rendszert használó applikáción keresztül kezdeményezted és 
a linkre kattintva valamilyen okból nem az adott applikáció oldalára irányítana vissza látogass el újra az applikáció oldalára


kattintandó  link


* * * * * *

linkre kattintva érkező oldal szöveg:

"Az ADA rendszerében regisztrációd és az általad használt email cím igazolásra került."

**Comment by magwas** [comment]
többi email?

**Comment by krosza** [comment]
most csinálom

**Comment by krosza** [comment]
def sendPasswordResetMail(self, user, secret, expiry):

Ezt a levelet azért kaptad, hogy pótolni tud az elfelejtett jelszavadat. Ha a jelszó cserét nem te kezdeményezted akkor ne csinálj semmit.

A lenti linkre kattintva az ADA oldalán megadhatod az új jelszavadat.

**Comment by krosza** [comment]
def sendDeregisterMail(self, user):

Ezt a levelet azért kaptad mert az ADA oldalán kezdeményezted a regisztrációd megszüntetését az ADA rendszerében 
és ezzel együtt valamennyi adatod törlését az ADA rendszerből. Amennyiben nem te kezdeményezted a regisztrációd
megszüntetését akkor hagyd figyelmen kívül ezt a levelet.

Amennyiben az alábbi linkre kattintasz,  akkor az ADA rendszeréből valamennyi adatod törlésre kerül és az ADA 
felhasználói fiókod is  megszűnik. Elveszik valamennyi, az ADA rendszerében meglévő igazolásod, beleértve a személyes
tanúsítás során megszerzett igazolásokat is. Azokat a webes szolgáltatásokat és mobil applikációkat, melyeket az ADA 
rendszerének használatával értél el többé már nem fogod tudni elérni.
