### ISSUE TITLE
landing page javítanivalók

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#322]
- a home oldalon a slide-ok beugranak egy pillanatra, eltűnnek, és utána úsznak be. Ez így zavaró
- a "mi ez?" oldalon nem mennek a "részletek" gombok
- fent a "rólunk" link a "kik vagyunk" helyett a "mire jó ez" oldalra ugrik.
- a "csapat" még nincs meg.
- a "blog" sincs meg
- a "kapcsolat" sincs meg
- a "mire jó ez"-hez kellenének use case-ek
- a statisztikába kellenének számok
- bemutatkozó video és szövegek mellé
- legalul az impresszumot is át kellene írni
- az oldalba kerülő emailcímekről kéne jegy, hogy hozzam létre, és hogy kinek menjenek.

**Comment by magwas** [comment]
http://patyicivil.hu/ada/index.html

**Comment by krosza** [comment]
hol van ez most?
ideraknád a linket?
