### ISSUE TITLE
landing page content

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#323]

**Comment by magwas** [comment]
Magosányi Árpád
Backend Development

Egyszer gyíkká változtattak, de már elmúlt.

kép; fb-s profilképem
fb: https://www.facebook.com/arpad.magosanyi
mail: mag@magwas.rulez.org

**Comment by madcsaba** [comment]
Madarász Csaba
kommunikáció

Madár lakozik a földigilisztában és a nagy szellem pihen mindegyik fűszálban!

kép; fb-s profilképem 
fb: - ada fb oldal
mail.: csaba@opengovernment.hu  (egyébként mondjad@adatom.hu)
linked in https://hu.linkedin.com/in/madaraszcsaba
twitter.: www.twitter.com/nyiltkormanyzas
