### ISSUE TITLE
különlogin oldal az alkalmazások kiszolgálásához

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#341]

**Comment by Claymanus** [comment]
https://sso.edemokraciagep.org/login.html?next=https%3A%2F%2Fsso.edemokraciagep.org%2Fada%2Fv1%2Foauth2%2Fauth%3Fresponse_type%3Dcode%26client_id%3D3d56a1bf-75fe-4d0a-aa4b-dc01c116ad25%26redirect_uri%3Dhttps%253A%252F%252Fszabadszavazas.hu%252Fsso_callback%253FSSO_action%253Dlogin%2526_wpnonce%253D4f4d38d96a%2526need%253Dhashgiven%2526wp_redirect%253D%252F

**Comment by krosza** [comment]
A hash kikényszerítése benne van vhol?

**Comment by Claymanus** [comment]
ja, a fenti linkkel tesztelheted

**Comment by krosza** [comment]
vmi ilyesmi szöveget be kellene raknunk a reg. részre még:
"A regisztráció során megadott email címedre küldünk neked  egy levelet,
melyben lévő linkre kattintva két napon (egy héten?) belül vissza kell
igazolnod hogy te vagy az email cím tulajdonosa."

**Comment by krosza** [comment]
undefined  - ez mit jelent, akkor jött elő amikor próbáltam titkos kódot csinálni egy meglévő  fiókhoz

**Comment by krosza** [comment]
szöveget hol lehet rajta változtatni?

az alábbi lenne a javaslat:

he szabadszavazas.hu application needs you have the assurances below  - 
A szabadszavazas.hu oldal kéri, hogy készíts magadnak Titkos Kódot

"Elkészítem a Titkos Kódom

A Titkos Kód elkészítéséhez szükséges adatokat nem tárolja a rendszer. Az alább megadott személyes adataidból a "Titkos Kód Gép" segítségével előállított kódot őrzünk meg, melyekből az eredeti adatok nem nyerhetők vissza. A Titkos Kódot magad is előállíthatod , és akkor csak azt kell bemásolnod a lenti "Tikos Kód" mezőbe"

új szöveg:

"A Titkos Kód elkészítéséhez szükséged  lesz  a Lakcímkártyád  hátoldalán szereplő Személyi azonosítódra. 
 A Titkos Kódot magad is előállíthatod , és akkor csak azt kell bemásolnod a lenti "Tikos Kód" mezőbe."

**Comment by Claymanus** [comment]
itt azért tartsuk szem előtt azt, hogy a cél ezzel a felülettel nem az hogy a meglévő regisztrációs oldal információtartalmával egyenértékű dolog jöjjön létre, hanem hogy a legfontosabb mezőkön keresztül a lehető leggyorsabban infóhoz jusson a rendszer. Ergo nem itt kellene megmagyarázni a dolgokat, hanem nyugodtan küldjük el a usert egy linkkel a releváns info oldalakra. Annak semmi értelme nincs, hogy csinálunk ugyanarra még egy UI-t.

**Comment by Claymanus** [comment]
ja, amúgy meg ha bugot találsz a login.html-ben, akkor kérlek csinál neki új jegyet

**Comment by krosza** [comment]
teljesen jogos, ezért is húztam meg a titkos kód szöveget
az email figyelmeztetést azért tartottam fontosnak mert a tipikus szsz  user vleg nem fog az ada oldalán bóklászni, ez a normál ada oldalon sem szerepel még, sztem oda is vhová be kellene rakni

**Comment by Claymanus** [comment]
link email+hash teszteléshez:
https://sso.edemokraciagep.org/login.html?next=https%3A%2F%2Fsso.edemokraciagep.org%2Fada%2Fv1%2Foauth2%2Fauth%3Fresponse_type%3Dcode%26client_id%3D3d56a1bf-75fe-4d0a-aa4b-dc01c116ad25%26redirect_uri%3Dhttps%253A%252F%252Fszabadszavazas.hu%252Fsso_callback%253FSSO_action%253Dlogin%2526_wpnonce%253D4f4d38d96a%2526need%253Dhashgiven,emailverification%2526wp_redirect%253D%252F
