### ISSUE TITLE
wp blog az adatomnak

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#346]

**Comment by Claymanus** [comment]
ezt miért zártad le?

2016.03.07. 17:11 keltezéssel, Árpád Magosányi írta:

**Comment by magwas** [comment]
Done-ba tetted, mert duplicate :)

**Comment by Claymanus** [comment]
2016.03.07. 20:19 keltezéssel, Árpád Magosányi írta:
>
> Done-ba tetted, mert duplicate :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/edemo/PDOauth/issues/346#issuecomment-193404925>.
>
ja, ok
