### ISSUE TITLE
footer linkek beállítása

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#350]
landing page-en

**Comment by magwas** [comment]
kihide-olni

**Comment by Claymanus** [comment]
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Licenc" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><a xmlns:cc="http://creativecommons.org/ns#" href="e.demokracia.rulez.org" property="cc:attributionName" rel="cc:attributionURL">KDányE Alapítv</a> <span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">ADA - Anonim Digitális Azonosító Szolgáltatás</span> című műve <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Nevezd meg! - Így add tovább! 4.0 Nemzetközi Licenc</a> alatt van.
