### ISSUE TITLE
emailből emailverification

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#364]

**Comment by magwas** [comment]
https://github.com/edemo/PDOauth/blob/master/src/end2endtest/config.py
Ebben látod a példa email kontentet, az url paraméterekkel.

**Comment by Claymanus** [comment]
https://sso.edemokraciagep.org/fiokom.html?section=emailcheck

**Comment by magwas** [comment]
adatom.hu-n beállítva. teszteld

**Comment by Claymanus** [comment]
ez a teszt szerveren megy
