### ISSUE TITLE
404 not found - deregister

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#405]
https://sso.edemokraciagep.org/ada/v1/users/gypeng@drezina.hu/deregister

**Comment by magwas** [comment]
@DECORATOR.interfaceFunc("/v1/deregister", methods=["POST"], formClass=DeregisterForm, checkLoginFunction=CONTROLLER.jsonErrorIfNotLoggedIn)

**Comment by magwas** [comment]
class CSRFForm(Form):
    csrf_token = TextField('csrf_token', validators = csrfValidator)

class DeregisterForm(CSRFForm):
    pass

class DeregisterDoitForm(CSRFForm):
    deregister_secret = TextField('deregister_secret', secretValidator)
