### ISSUE TITLE
A javascript két példányban van.

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#406]
static/fb.js vs static/js/fb.js
static/script.js vs static/js/script.js
satöbbi.
Az egyiket mindegyikből tötölni kéne, miután megoldottuk hogy senki se azt használja.

**Comment by Claymanus** [comment]
ez azért van így, hogy a régi meg az új ui is tudjon működni egyszerre.
Értelemszerűen amint késznek tekintjük az új UI-t, a régi scriptek, css-ek a static gyökérből törölhetőek
