### ISSUE TITLE
email change interface

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#409]
Nem találtam ilyet a main.py-ban, egyáltalán van az email-change funkció implementálva?

**Comment by magwas** [comment]
interface:
- changeEmail
 - bejelentkezett felhasználó használhatja
 - post
 - csrf token és új emailcím kell neki
 - csinál egy changeemail temporary credential-t
 - küld egy értesítő levelet a régi és az új emailcímre is. abban lesz egy confirmation url: EMAIL_CHANGE_CONFIRMATION_URL
 - törli az összes lejárt changeemail temporary credet
- confirmChangeEmail
  - az EMAIL_CHANGE_CONFIRMATION URL-en a ui hívja
  - post
  - paraméter: confirm
  - ha a confirm true, akkor átírja az emailcímet
  - törli a temporary credential-t

kell majd hozzá UI.

**Comment by Claymanus** [comment]
cancel/revoke hiányzik a folyamatból.
ha az új címre küldött levélből jön a confirm oldalra, nem kell email validációs folyamat.

**Comment by magwas** [comment]
cancel/revoke nem lesz beépítve.  A régi emailcímre küldött email tartalmazza az offline folyamat indításához szükséges infót.
