### ISSUE TITLE
500 - reg with keygen

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#417]
- iframe-be targetoltam a keygen submitot, hogy detektálni lehessen amikor kész. 500-at dobott a szerver.
- target _blankba ugyenez. de az 500-at úgy dobja, hogy a usert amúgy meg létrehozza, mert legközelebb már nem fogadja le az emilt. Valszeg az előbb is megcsinálta a usert.
- target nélkül is dobja

**Comment by magwas** [comment]
nem tudom reprodukálni.

**Comment by Claymanus** [comment]
uj ui, chrome

**Comment by Claymanus** [comment]
lessons learned:
- Chromban ha sikeresen mentődött a kulcs,
-- a javascript megáll, a submit hívás utáni rész már nem fut le.
-- a target iframe onload metódusa nem fut le
