### ISSUE TITLE
hash ütközés kezelése

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#418]
mikor megadom a titkos kódom, meg kellene nézni, hogy van e már ilyen hash regisztrálva, ha ütközés van jó lenne ha értesítést kapna a user:
- van már ilyen hash de nincs tanúsítva, mielőbb csináld meg  a tiéd és akkor a másikat  ( kérdés a hash-t vagy a fake felhasználót is?) töröljük
- van már ilyen hash és tanúsítva van, ha úgy gondolod ellopták a személyiséged jelentsd azonnal....
ezek a reg után automatikusan mennének ki

**Comment by magwas** [comment]
A jelenlegi funkcionalitás lentebb.
Egészen pontosan mivel kellene kiegészíteni?

http://adadocs.demokracia.rulez.org/html/documentation.html#d54e419
When a hash is registered which is already used by another user, the user is notified about the fact.
When a hash is registered which is already used by another assured user, the user is notified about the fact and registration fails.

http://adadocs.demokracia.rulez.org/html/documentation.html#d54e355
When an assurer wants to add an assurance for a user with hash and without email, and there are multiple users with that hash, then an error is signaled.
When an assurance added with hash and email, and there is another user with the same hash, the hash from the other user is deleted.
Adding assurance with invalid hash and email fails.
Adding assurance with invalid hash and no email fails.
Adding assurance with email and hash of someone other fails.

**Comment by krosza** [comment]
Email értesítésre gondoltam igazából, de ha az felesleges akkor egy magyarázó hibaüzenet szöveg is jó lenne

**Comment by krosza** [comment]
When a hash is registered which is already used by another assured user, the user is notified about the fact and registration fails.

erre az esetre nem találtam    #: src/pdoauth/Messages-t

**Comment by magwas** [comment]
"another user is using your hash" hu.po:103
