### ISSUE TITLE
szerver üzenetek fordítása

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#421]
találjuk ki, hogy legyen!
Tudsz generálni egy listát, hogy milyen szerverüzenetek vannak?

**Comment by magwas** [comment]
https://raw.githubusercontent.com/edemo/PDOauth/develop/src/pdoauth/Messages.py

**Comment by Claymanus** [comment]
Ez tök jó. De ha ez amúgy is gettextes, akkor most mégis csináljam js-ben?

**Comment by magwas** [comment]
ezen kívül két bonyolultabb eset van. 

    msg = '["{2}","{0}","{1}"]'.format(neededAssurance, user.email,addedAssurance)

és

    raise ReportedError("{0}: {1}".format(missingRequiredParam, name))

Ezeket neked kell parse-olnod.

**Comment by Claymanus** [comment]
amúgy hol a po file?

**Comment by Claymanus** [comment]
az oké hogy rámteszed ezt a jegyet, de jó lenne tudni, hogy mit csináljak?
Fordítsam le a po file-t? Akkor, kellne egy link.
Ha meg a frontenden js-ben kell fordítani, akkor kellenének a stringek, meg hogy mikor jönnek.




2016 Március 8, Kedd 13:10 CET dátummal, Árpád Magosányi <notifications@github.com> ezt írta:
 
Assigned #421 to @Claymanus.

**Comment by magwas** [comment]
találjuk ki, hogy legyen. Nézd meg az üzeneteket, és beszéljünk róla demo-n.
