### ISSUE TITLE
reg with ssl

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#428]
létező assurált hash-el regisztrált user hibaüzenetet kap, ez eddig ok, de az emil címe regisztrálódik, így nem tud regisztrálni többet. Úgy néz ki, ez minde keygen hiba esetén előfordul lsd: #417

**Comment by magwas** [comment]
Az alapprobléma a hash ütközés.
Lehet hogy az lenne a korrekt megoldás, hogy a szerver csak elemi műveleteket végez, és a UI pakolja őket össze egybe. Tehát a regisztráció és a hash megadása két külön ajax hívás lenne.
?

**Comment by Claymanus** [comment]
Ettől még probléma marad, hogy a user emilcíme regisztrálódik, és kulcs nélkül nem tud bejelentkezni. Ez vonatkozik más anomáliák miatt meghiúsult kulcs telepítésre is.
