### ISSUE TITLE
error branches in javascript

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#43]
Some error cases are not nicely handled in javascript.

**Comment by Claymanus** [comment]
this issue comes from python, the request returns the html content, and this will be displayed in error container.

**Comment by magwas** [comment]
The reply is a redirect to the start page, so when someone is not logged in, she can login. This functionality should not be lost for some of the pages. Let's work out more exact rules on when to redirect and when to just return a 403.

**Comment by Claymanus** [comment]
the redirection isn't needed, the ui can handle the error messages comes trough the ajax

**Comment by magwas** [comment]
there should be two login checks. one for html and one for ajax.
