### ISSUE TITLE
pw csere landing felület gombra doRedirect(fiokom)

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#432]

**Comment by magwas** [comment]
[{"username": null, "hostname": "izeke.org", "name": "myapp", "can_email": null, "email_enabled": null}, {"username": "4124bdba30e98dd3", "hostname": "szabadszavazas.hu", "name": "szabadszav", "can_email": null, "email_enabled": null}, {"username": "57fefa4ff0ea68e3", "hostname": "li-de.tk", "name": "li-de", "can_email": null, "email_enabled": null}, {"username": null, "hostname": "patyicivil.hu", "name": "patyicivil", "can_email": null, "email_enabled": null}]

**Comment by Claymanus** [comment]
ezmiez?
