### ISSUE TITLE
SSL_LOGOUT

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#437]
Az uris által küldött SSL_LOGOUT link 404.et ad
{"ANCHOR_URL": "https://testanchor.edemokraciagep.org/", "BACKEND_PATH": "/ada", "BASE_URL": "https://sso.edemokraciagep.org", "FACEBOOK_APP_ID": "517253418423328", "PASSWORD_RESET_FORM_URL": "https://sso.edemokraciagep.org/fiokom.html", "SSL_LOGIN_BASE_URL": "https://sso.edemokraciagep.org:8080", "SSL_LOGOUT_URL": "https://sso.edemokraciagep.org/ssl_logout/", "START_URL": "https://sso.edemokraciagep.org/fiokom.html"}

ha nem jó semmire sem akkor vegyü ki, ellenkező esetben jó lenne, ha működne

**Comment by magwas** [comment]
Ez lett volna az az url, amin a böngészővel elfelejtetjük a site-hoz rendelt certet. Csináltam egy oldalt, ami redirectel a start url-re.
