### ISSUE TITLE
szerver üzenetek fordítása

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#445]

**Comment by magwas** [comment]
https://github.com/edemo/PDOauth/blob/master/messages.pot

**Comment by Claymanus** [comment]
https://github.com/edemo/PDOauth/blob/develop/messages.pot

**Comment by magwas** [comment]
Most már ezt kell fordítani. Bocs a kavarásért:
https://github.com/edemo/PDOauth/blob/develop/hu.po

**Comment by krosza** [comment]
ebbe bele tudnátok rakni a lefordítandó assurance -Igazolás listát

**Comment by magwas** [comment]
486-os pull request-el bekerültek, + új string. Azt akkor dobja, amikor valamilyen emailt akar küldeni, de a mail szerver hibát dob.

**Comment by krosza** [comment]
ez kész

**Comment by krosza** [comment]
https://github.com/edemo/PDOauth/blob/develop/hu.po

404 hibát dob, 

a develop-ban és a masterben is a régi van benne a kijavítoott eltünt

**Comment by Claymanus** [comment]
https://github.com/edemo/PDOauth/blob/develop/static/locale/hu.po

ez a po végleges helye, hogy elérjék a scriptek is

**Comment by krosza** [comment]
es a legutolsó javított verzió valahol elérhető?
