### ISSUE TITLE
UI for my applications

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#463]
(not blocking!)
http://adadocs.demokracia.rulez.org/PDOauth/develop/html/documentation.html#d54e120

**Comment by Claymanus** [comment]
Már csináltam magamnak ilyet, ezt lezárhatod, csak előbb dobb bele a 
jegyembe #432, hogy hogy néz ki a json object, ami jön

2016.03.10. 16:22 keltezéssel, Árpád Magosányi írta:
