### ISSUE TITLE
Fiókom, tanúsítói felület  szöveg javítása

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#469]
https://adatom.hu/fiokom.html

**Comment by Claymanus** [comment]
mit kell javítani azt is írd ide

**Comment by krosza** [comment]
"A felhasználó email címe"      -  A Felhasználó email címe  
"Igazolás kiadása"   -     Az adatok  ellenőrzése
"Kiadható assurancok:"  -   Kiadható igazolások
