### ISSUE TITLE
user sets app can email

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#476]
@DECORATOR.interfaceFunc("/v1/setappcanemail", methods=["POST"], checkLoginFunction=CONTROLLER.jsonErrorIfNotLoggedIn,
    formClass = AppCanEmailForm)

class AppCanEmailForm(CSRFForm):
    appname = TextField('appname', userNameValidator)
    canemail = BooleanField('canemail')

    @test
    def logged_in_users_can_disable_an_app_to_send_email_to_them(self):
        self.assertUserSetTheMap(app, False, 'false')

    @test
    def logged_in_users_can_enable_an_app_to_send_email_to_them(self):
        self.assertUserSetTheMap(app, True, 'true')

    def chooseAppWithOppositeEmailCapability(self, canEmail):
        for appName in self.appNames:
            theApp = Application.find(appName)
            theMap = AppMap.get(theApp,self.user)
            if theMap.can_email is not canEmail:
                return theApp
        
    def assertUserSetTheMap(self, app, theCase, theString):
        with app.test_client() as c:
            theApp = self.chooseAppWithOppositeEmailCapability(theCase)
            self.login(c, self.user)
            csrf = self.getCSRF(c)
            data = dict(
                csrf_token = csrf,
                appname=theApp.name,
                canemail=theString)
            resp = c.post("/v1/setappcanemail",data=data)
            self.assertEqual('200 OK', resp.status)
            self.assertEqual(theCase, AppMap.get(theApp,self.user).can_email)

**Comment by Claymanus** [comment]
úgy csinál mintha a beállított értéket eltenné, mert az ajax hívás válaszában a beállított érték van, de nem menti el, mert ha újratöltöm az oldalt, a régi értékkel jön a getapps

**Comment by magwas** [comment]
most csekkold le, elvileg működnie kell. Ehhez a javításhoz nem tudtam tesztet kitalálni, azért vagyok ilyen bizonytalan...

**Comment by Claymanus** [comment]
mux
