### ISSUE TITLE
hide ami nincs a landing page-ben

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#478]
És a hátterek legyenek egyszerű egyszínűek

**Comment by Claymanus** [comment]
részletezd plíz, nem vágom mit akar ez a jegy

**Comment by magwas** [comment]
Mivel Csabára egy ideig nem számíthatunk:
Azokat a dolgokat, amik nincsenek készen a landing page-en, el kell hide-olni.
A háttérképekpedig egyszerűek legyenek, hogy a grafikusok tudjanak miből dolgozni.
Károlyt kérdezd arészletekért.

**Comment by krosza** [comment]
JAVASLATOM:
a landing page , a hogy működik, Rólunk oldalakat egyelőre rakjuk félre
https://sso.edemokraciagep.org/index.html
https://sso.edemokraciagep.org/user_howto.html
https://sso.edemokraciagep.org/about_us.html

Mert ez így nagyon lerontja a mögötte lévő cucc kiválóságát
- nincs egységes design, SZÍN, BETŰ, KÉPEK ,UI KONCEPCIÓ
- a szövegek önismétlők össze vissza vannak
- nem egységesek koncepcionálisan 
a funkcionális oldalak viszont tök rendben vannak, és még megjelenésükben is vállalhatóak
ezek alapján kellene megcsinálni  a funkcionális lapokkal megegyező design-al  3 egyszerű html lapot helyettük
egyedül a menüsort és a láblécet hagynám meg, és az oldalsó menüt a két kifejtős oldalon
ha elfogadjátok akkor a meglévő szövegekből a 3 html szövegét összevágnám  és a hétvégén megcsinálnám
ezzel el tudnánk indulni szerdán, és ha már működik a dolog keresünk egy ui csapatot akik akik csinálnak valami ütőset e helyett a 3 egyszerű oldal helyett

Bocs ezért, csak sokat molyoltam a szöveggel és sehogyan sem állt össze

mi a véleményetek?

**Comment by krosza** [comment]
itt van amit kiraknék egyelőre:

https://www.gitbook.com/book/edemo/adatkezelesi-szabalyzat-az-ada-szolgaltatashoz/details

**Comment by Claymanus** [comment]
A szabályzatok nem maradnak a kitbook-on? Nem úgy volt, hogy onnan linkeljük?

**Comment by krosza** [comment]
rossz linket írtam az előbb ezt akartam:
https://docs.google.com/document/d/1pj1Cp0mC2sd6q-P50m3wL4-HcxWOHxkymQ1ERDwh7Fo/edit

vagyis a 3 db  html oldalra ezeket a szövegeket  raknám ideiglenesen

**Comment by krosza** [comment]
BERAKTAM A MENÜT ÉS A LÁBLÉCET IS 

https://docs.google.com/document/d/1pj1Cp0mC2sd6q-P50m3wL4-HcxWOHxkymQ1ERDwh7Fo/edit
