### ISSUE TITLE
tanúsítói felületena  hash megjelenítése

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#501]
átgondolandó, hogy a tanúsítónak miért kell látni magát a hash-t, ezzel ő össze tudja kötni az email címeket a hash-ekkel szinte képes felépíteni a a védett adatbázist:.

 javaslat: az ellenőrzés során a "Kód előállítására csak az jelenjen meg, hogy a "A Felhasználó Titkos Kódja az  ellenőrzéshez elkészült".

**Comment by Claymanus** [comment]
Átalakítottam, nézd meg hogy jó-e így

**Comment by krosza** [comment]
én defaultból nem írnék semmit  bele, csak azután, ha beírta, és sikeres az előállítás
azt hogy  "A Felhasználó Titkos Kódja az ellenőrzéshez elkészült".
 nekem egyelőre hibaüzenetet dob egyébként

**Comment by Claymanus** [comment]
Ez a szekció nem "ellenőrzés" hanem "igazolás kiadása". Az ellenőrzés túl agresszív szerintem, nem használnám ezt a terminológiát a kommunikációnkban sehol sem.
A piros keretben lévő üzenetre azért van szükség, mert lehetséges, hogy elrontotta az adatok bevitelét, és mivel a hash mező most nem látszódik, szükség van valamire, ami jelzi, hogy a hash mező most OK, vagy nem. pl az előbb ugyan OK volt, de észrevettem hogy elböktem egy betűt az anyja nevében, és újra kérem a hasht, akkor először törlődik a hash mező, így ha ez a kérés nem eredményez hasht, akkor látnunk kell, hogy nincs hash, a mezőben.

**Comment by krosza** [comment]
ok, használjuk akkor az " A Titkos Kód egyeztetése" kifejezést 
a piros mező ok legyen benne vmi csak nekem ez félre érthető, azt jelenti, mintha  a felhasználó még nem készítette volna el a hasht
