### ISSUE TITLE
FB regisztráció

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#545]
itt:  https://sso.edemokraciagep.org/fiokom.html?section=registration

probálok FB-s  reget, de egy ilyen hibaüzenet jön:

![uploads/c3635c69-099a-4d8c-a4ea-ed4dab9faf03/fb reg.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc3635c69-099a-4d8c-a4ea-ed4dab9faf03%2Ffb+reg.JPG)

miért kell neki ilyenkor pw?
miért angol?
mit keres lent egy keygen gomb?

**Comment by magwas** [comment]
A hibaüzenetet nem tudom reprodukálni. nekem sikerült az fb regisztráció.

**Comment by magwas** [comment]
Nem lehet, hogy ez is a refresh probléma, a hidden mezőben van jelszó?
Milyen böngészővel nézed, milyen verzió?

**Comment by krosza** [comment]
nem lehet az hogy olyan emailnél csinálja  csak amelyet korábban töröltem a rendszerből ( nálam több böngészőben ezt csinálja)

**Comment by krosza** [comment]
Ilyenkor az FB email címnek egyezni kell azzal amit az adába írok?

"Válaszd ki hogyan akarsz regisztrálni"

pl próbálom ue.-t  Explorer 11-ben rányomok az FB ikonra és ez jön fel:

![fb reg 2](https://cloud.githubusercontent.com/assets/12797314/13892185/ed4ab0ce-ed55-11e5-9d44-92ae9f348976.JPG)
???

**Comment by Claymanus** [comment]
a {0} azért van mert a gettext nem dolgozza fel a stringbe injektált adatokat. Ez nyilván egy külön bug.

**Comment by Claymanus** [comment]
a keygen gomb ideiglenesen van ott, hogy tesztelni tudjam a javascriptes crypto funkciókat, értelemszerűen élesben nem lesz ott

**Comment by Claymanus** [comment]
@krosza amikor az fb gombra kattintasz, lekérdezi a javascript az fb-től az adataidat és kitölti az email mezőt és a hidden azonosító mezőt (azonosító=usernév) meg a hidden secretbe jön egy access token.
Ha nem kapott a cucc adatot az fb-től akkor ezek a mezők üresek, és ha üres mezőkkel próbálsz regisztrálni, akkor ez az üzenet jön.

**Comment by Claymanus** [comment]
a {0} bug: Javítva

**Comment by Claymanus** [comment]
Az adatnélkül visszatérő facebook hibára vettem fel egy másik jegyet: #558
Az angol hibaüzenetre is: #557
ezt zárom
