### ISSUE TITLE
reg. pw-el

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#546]
1,követeli a user nevet holott oda van írva, hogy nem kötelező

2. ha refresh-t nyomok nem törli ki az előzőleg beírt email címet és a checkbox kijelölést sem

**Comment by magwas** [comment]
Tényleg követeli a usernevet. A hibaüzenet nincs magyarítva.

**Comment by magwas** [comment]
Nekem refreshre kitörli az előzőleg beírt email címet és a checkbox kijelölést is.

**Comment by Claymanus** [comment]
ezt a szerver követeli ;-)

**Comment by magwas** [comment]
Ha nincs usernév, a UI elküldi az emailcímet
