### ISSUE TITLE
Fiók törlése nem működik

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#547]
https://sso.edemokraciagep.org/fiokom.html?section=deregistration&secret=cbaaa90d-8e7e-4353-a277-ccedabb92f54

"Hibás jelszó"   
???
jelszót követel, hozzá de nincs mező, ahova be lehetne írni

**Comment by krosza** [comment]
úgy tűnik a jelszó és az igazolások törlése megtörtént de a reg megmaradt

**Comment by magwas** [comment]
Nekem a fenti URL-re azt mondja, hogy "nem vagy bejelentkezve".

**Comment by krosza** [comment]
ez a felhasználó: charlie@noba.hu
ha ezt törölni akarom adja az alábbi hibát

![uploads/fee269e5-4c59-4d7d-97cf-6735dd92a9e8/törlés hiba.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffee269e5-4c59-4d7d-97cf-6735dd92a9e8%2Ft%C3%B6rl%C3%A9s+hiba.JPG)

**Comment by Claymanus** [comment]
@krosza a hibás jelszó üzenet a fordítás hibája. Ugye itt egy secret jön az emailből. Ha ez hiányzik akkor nem tudunk fiókot törölni.
Tekintettel arra, hogy a secret a linkben ott van, fogalmam sincs hogy miért üzeni a szerver, hogy nincs secret. Ugyanis nálam működik, nem tudom reprodukálni. A screenshoton nem látszik sajnos a böngésző url mezője. Meg az sem, hogy ez milyen böngésző.
@magwas /v1/deregister_doit csrf tokent is kér, ergo jogos a hibaüzenet, hogy nem vagy bejelentkezve. Konkétan ez jön a szerverből.

**Comment by krosza** [comment]
itt van egy másik kép hozzá


![uploads/51e26046-abcd-4890-8394-c8b26bc46423/törlés hiba 2.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F51e26046-abcd-4890-8394-c8b26bc46423%2Ft%C3%B6rl%C3%A9s+hiba+2.JPG)

**Comment by Claymanus** [comment]
passzolom. majd @magwas megmondja, mikor küld ilyen üzenetet a szerver. Én nem tudom reprodukálni.

**Comment by magwas** [comment]
a "Hibás jelszó" a "Bad deregistration secret" fordítása a hu.po-ban.
Akkor kapod, ha az a secret, amit ott az url-ben látsz, nem érvényes (pl. már egyszer használtad).

**Comment by krosza** [comment]
ok ezt javítom majd de ez akkor is egy hiba nem tudom ezt fiókot törölni:
charlie@noba.hu

**Comment by krosza** [comment]
erre javítottam,

"A fiók törlésének lehetősége már nem érvényes. Ha törölni akarod a fiókod próbáld meg még egyszer!"

**Comment by Claymanus** [comment]
500-at dob, de a háttérben az összes credential-t törli, nézd meg a logokat, nekem ezzel csinálta: info@patyicivil.hu
URL: https://sso.edemokraciagep.org/fiokom.html?section=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700

**Comment by magwas** [comment]
Mar 20 16:32:44 sso mod_wsgi: [:error] [pid 23974:tid 140533063407360] [client 212.48.246.224:55885] IntegrityError: (IntegrityError) update or delete on table "user" violates foreign key constraint "app_map_user_id_fke
y" on table "app_map", referer: https://sso.edemokraciagep.org/fiokom.html?section=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700
Mar 20 16:32:44 sso mod_wsgi: [:error] [pid 23974:tid 140533063407360] [client 212.48.246.224:55885] DETAIL:  Key (id)=(112) is still referenced from table "app_map"., referer: https://sso.edemokraciagep.org/fiokom.html
?section=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700
Mar 20 16:32:44 sso mod_wsgi: [:error] [pid 23974:tid 140533063407360] [client 212.48.246.224:55885]  'DELETE FROM "user" WHERE "user".id = %(id)s' {'id': 112}, referer: https://sso.edemokraciagep.org/fiokom.html?sectio
n=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700
Mar 20 16:32:44 sso apache[23972]: sso.edemokraciagep.org:443 212.48.246.224 - - [20/Mar/2016:16:32:44 +0100] "POST /ada/v1/deregister_doit HTTP/1.1" 500 869 "https://sso.edemokraciagep.org/fiokom.html?section=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"


Mar 20 16:32:44 sso mod_wsgi: [:error] [pid 23974:tid 140533063407360] [client 212.48.246.224:55885]     return CONTROLLER.doDeregistrationDoit(form), referer: https://sso.edemokraciagep.org/fiokom.html?section=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700
Mar 20 16:32:44 sso mod_wsgi: [:error] [pid 23974:tid 140533063407360] [client 212.48.246.224:55885]   File "/usr/local/PDOauth/src/pdoauth/Controller.py", line 109, in doDeregistrationDoit, referer: https://sso.edemokraciagep.org/fiokom.html?section=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700
Mar 20 16:32:44 sso mod_wsgi: [:error] [pid 23974:tid 140533063407360] [client 212.48.246.224:55885]     self.removeUser(user), referer: https://sso.edemokraciagep.org/fiokom.html?section=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700
Mar 20 16:32:44 sso mod_wsgi: [:error] [pid 23974:tid 140533063407360] [client 212.48.246.224:55885]   File "/usr/local/PDOauth/src/pdoauth/Controller.py", line 97, in removeUser, referer: https://sso.edemokraciagep.org/fiokom.html?section=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700
Mar 20 16:32:44 sso mod_wsgi: [:error] [pid 23974:tid 140533063407360] [client 212.48.246.224:55885]     user.rm(), referer: https://sso.edemokraciagep.org/fiokom.html?section=deregistration&secret=4eb855c0-cb3e-4e12-b20a-f0682db0d700
