### ISSUE TITLE
index.html   statisztikák section, tanusító ikon

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#548]
A tanúsító ikonja nagyon elriasztó, nem tudnánk erre egy sokkal barátságosabb/kedvesebb jelet találni?

**Comment by magwas** [comment]
https://www.google.hu/search?q=certify&client=ubuntu&espv=2&biw=1023&bih=527&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjk2oren8vLAhVCWxQKHT8OBX4Q_AUIBigB#tbm=isch&q=man+thumbs+up+icon

**Comment by krosza** [comment]
pl vmi ilyesmi nektek?

![tumb up1](https://cloud.githubusercontent.com/assets/12797314/13893971/5e77d0a8-ed63-11e5-8f0d-b578e0af6f24.png)

**Comment by Claymanus** [comment]
innen válassz: http://fortawesome.github.io/Font-Awesome/icons/

**Comment by krosza** [comment]
http://fortawesome.github.io/Font-Awesome/icon/thumbs-up/
