### ISSUE TITLE
SSL kulcsos regisztráció

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#549]
Valahol elakad, illetve nem lehet tovább menni. Keygen gombra kattintva semmi sem történik, a a reg gombra kattintok akkor jön üzenet a böngészőből ( firefox) hogy generálta és installálta de utána vége, nem történik semmi  gondolom a böngésző  ok gomb után  megnyomása után kellene jutni a fiókomba

**Comment by magwas** [comment]
Az marad ki, hogy be is léptesse a felhasználót ilyenkor.
Szerintem nem blokker.

**Comment by Claymanus** [comment]
a firefox-nál nem tudom detektálni, hogy megjött az X509 cert, mert hiába targetálom a formot egy iframe-be, ha certet küld a szerver nem váltja ki az onload eventet. Ez chrome-ban működik.
ez az egész certes login így a keygennel elég használhatatlan:
- a chromban már nem működik
- az ie-ben eddig sem volt implementálva
- a firefoxban meg nem lehet detektalni
A megoldás hogy implementáljuk a javascriptes keygen funkciót pki library-val lsd: #keygen
A kérdés, hogy ezt most megcsináljuk a bétáig, illetve kiszedjük-e az ssl login funkciót. amíg nincs rendesen megoldva?
