### ISSUE TITLE
szerver oldali hibaüzenetek hiányoznak a po-ból

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#557]
pl ezek:
{"errors": ["secret: Field must be at least 8 characters long.", "secret: password should contain lowercase", "secret: password should contain uppercase", "secret: password should contain digit", "identifier: Field must be between 4 and 250 characters long.", "email: Invalid email address."]}

"Field must be.." konkrétan nincs is a po-ban. 
A többi benne van csak a kettőspont előtti rész nélkül
esetleg csinálhatnál ezekből assoc arrayt, de jó lenne ha a key is bekerülne a po ba.

**Comment by Claymanus** [comment]
Ez is:
https://sso.edemokraciagep.org/ada/v1/register

message: "you already have this hash: nothing is done"

**Comment by magwas** [comment]
A field must be.. rész valamelyik libben van.
A "you already have this hash: nothing is done" pedig új.

**Comment by magwas** [comment]
szerver oldal:
- a ":"-ot tartalmazó üzenetek szétcsapása
- a wtform ngettext lokalizálása
