### ISSUE TITLE
user_howto.html

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#565]
https://sso.edemokraciagep.org/user_howto.html

Az adatkezelés részben.

Az email-hez oda kellene írni, hogy nyugodtan hasnzáljon proxy email szolgáltatást, és javasolni pár ilyet.

"Az ADA rendszerében megszerzett igazolásaidat akkor adjuk ki az alkalmazások számára, ha ehhez hozzájárultál." Nem külön az igazolásokkal van ez, hanem megvan, hogy melyik alkalmazás mit kaphat, és az adott userhez vagy megkaphatja azokat, vagy nem.

**Comment by krosza** [comment]
beírtam.
"A regisztrációhoz nyugodtan használhatsz olyan email címet is, melyet csak erre a célra hoztál létre.Ezzel növeled a biztonságodat."

+ kihúztam  az igazolásos részt
