### ISSUE TITLE
dereg  nem működik még mindig

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#584]

**Comment by krosza** [comment]
itt próbálom 
https://sso.edemokraciagep.org/fiokom.html
 ezzel  krosza@gmail.com

**Comment by Claymanus** [comment]
mit ír ki?

**Comment by Claymanus** [comment]
@krosza ezzel mi a helyzet, még mindig nem megy? Dobjuk ki ezt a jegyet, ha megy.

**Comment by krosza** [comment]
működik
