### ISSUE TITLE
külön login hash

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#585]
undefined  hibát kapok mikor el akarom készíteni

**Comment by Claymanus** [comment]
egy kicsit pontosabban írd le a hibát: melyik oldal, melyik rész, mit írtál be, mire kattintasz stb

**Comment by krosza** [comment]
itt:
https://sso.edemokraciagep.org/login.html?next=https%3A%2F%2Fsso.edemokraciagep.org%2Fada%2Fv1%2Foauth2%2Fauth%3Fresponse_type%3Dcode%26client_id%3D3d56a1bf-75fe-4d0a-aa4b-dc01c116ad25%26redirect_uri%3Dhttps%253A%252F%252Fszabadszavazas.hu%252Fsso_callback%253FSSO_action%253Dlogin%2526_wpnonce%253D4f4d38d96a%2526need%253Dhashgiven,emailverification%2526wp_redirect%253D%252F#

és ez látszik:
![hash problema](https://cloud.githubusercontent.com/assets/12797314/13918727/5a077e80-ef69-11e5-82d1-6158d94690a5.JPG)

**Comment by Claymanus** [comment]
Nekem simán elkészíti ezt a hasht. Ez firefox?

**Comment by krosza** [comment]
igen

**Comment by Claymanus** [comment]
ez azért van, mert a tesztanchor ssl certje nem érvényes, ezért a ff eldobja a választ
Menj oda először https://testanchor.edemokraciagep.org/ add hozzá a biztonsági kivételt aztán jó lesz.
Ez az élesen nem lesz gond, mert ott hivatalos a cert

**Comment by krosza** [comment]
lehet, hogy csak engem nem szeret

**Comment by krosza** [comment]
igen ez volt a baj

2016-03-21 14:02 GMT+01:00 György Peng <notifications@github.com>:

**Comment by Claymanus** [comment]
új jegyet vettem ennek a certes dolognak a detektálására #586
