### ISSUE TITLE
külön login oldalak struktúrája

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#587]
kicsit egyszerűsítenék a dolgon, összesen 3 képernyőt csinálnék csak  (kép ide másolva):
belépés
reg
titkos kód készítés
szövegeket teljesen elhagynám azt majd az alkalmazás eldönti mit szeretne
a reg esetében egy lépésben történne minden

az is megfontolnám, hogy a T kód elkészítése és mentése ne legyen két külön gomb és magát a hash-t sem kell talán mutatni

**Comment by krosza** [comment]
![uploads/72af7c49-4b04-4606-9643-ee9b19e1363e/ada  külön login struktúre.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F72af7c49-4b04-4606-9643-ee9b19e1363e%2Fada++k%C3%BCl%C3%B6n+login+strukt%C3%BAre.JPG)

**Comment by Claymanus** [comment]
0. Kardinális: Az alkalmazások **nem** injektálnak szöveget az ADA UI-ba.
1. A szürke header kell - hogy tudja a user, hogy mi a fuckk történik
2. elfelejtettem szöveg kivehető - teszünk a gomb fölé egy vizszintes vonalat, illetve gomb title-be beírjuk a szöveget, ami csak akkor jelenik meg, ha sokáig tanyázik az egér a gomb fölött
3. A "válaszd ki a regisztráció módját" szerintem kell - semmiből nem lehet tudni egyébként, hogy mik azok a gombok, ha nem írjuk oda.
4. a szövegmezők a módválasztó gomboknak megfelelően jelennek meg.
5. nem szeretném elhájdolni a usernév mezőt - vannak olyan degeneráltak mint én, hogy n az ezrediken emílcímet használnak, de csak egy usernevet. Ha elfelejtem melyik emílcímemmel regeltem, elég nagy szarban vagyok.
6. karakterszám elvárás kivehető - betehetjük title-ba
7. ne legyen digest getter a regisztráció oldalon -  ha az alkalmazásnak kel a hash, úgyse tud továbbmenni a user, ha nincs neki hash given assuranca
8. assurance checker most ugye konkrétan a szsz miatt épült be - de ha már beépült, akkor semmiképp nem korlátoznám le csak a digest getter-re, másoknak más kellhet. 
9. Az assurance checker alapértelmezésben egy listával jön fel, amiben az alkalmazás által igényelt cuccok vannak. Ki van pipálva, ami megvan, és egy gomb van annál, ami hiányzik. Addig nem irányít vissza a felület az alkalmazáshoz, amíg nincs meg minden. Hacsak nem teszünk ki ide egy "haggyámá" gombot, ami elereszti a usert. Az alkalmazás oldalon amúgy is kell legyen egy újabb checking.
10. a digest getterben lehet váltogatni a hash mezőt és a személyiszám/anyja neve szekciót annak fügvényében, hogy melyik gombot nyomta meg. Ha elkészítjük itt, a "A kód előállítása" gomb kezdeményezheti a kapott hash automatikus mentését. Ekkor nem jelenik meg a "titkos gomb mentése" és a hash mező sem.
11. Az adatok átadására vonatkozó confirm felület is kell. (Volt rá hibajegy is, ezért is tettem bele) Bár most még nincs szerver oldalon implementálva, hogy a user engedélyezheti, hogy egy alkalmazás lekérheti-e az adatait, vagy sem, ez alapértelmezés szerint tiltva lesz, és ezen a felületen lehet engedélyezni.

**Comment by Claymanus** [comment]
Ja és az az elvetemült gondolatom, hogy ez a login felület lehetne a fiókom.html login felülete is majd később, nem kell külön login rész oda. - A login menüre kattinva simán feljön egy kis kocka modal a login felülettel, aztán ha sikerült belépni megjelenik a fiókom rész. A regisztrációnak lehet csinálnék egy külön szájbarágós html-t.
