### ISSUE TITLE
missing links - email address validation email

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#589]
érvényesíted a regisztrációdat az Anonim Digitális Azonosító (ADA) rendszerében és
    elfogadod az ADA Felhasználási Feltételeit (link) és a Közösségi Digitális Eszközök Alapítvány Adatkezelési Tájékoztatóját.(link)

**Comment by magwas** [comment]
az sso.edemokraciagep.org-on megcsináltam. Az adatom.hu-n már megvolt.

Károly, leellenőrzöd? A password verification email az.

**Comment by krosza** [comment]
adatom.hu rendben
e dem a jelszó felismerő eltörött nem enged be, de reget se. a hogy a
629-es hiba jegybe írtam

**Comment by magwas** [comment]
Most már megjavítottuk az sso-t
