### ISSUE TITLE
szöveges ember szerzése

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#612]
1. körben próbáljuk meg Batta Orsit.

**Comment by Claymanus** [comment]
szia Orsi
Tudnál nekünk segíteni?
Csináltunk egy ADA (anoním digitális azonosító) szolgáltatást, amivel lassan elindulnánk.
Viszont nem vagyunk biztos benne, hogy az oldalon lévő szövegek érthetőek a nagyközönség számára.

Ok
En elegge laikus vagyok. wink hangulatjel

Arra szeretnélek kérni, hogy nézd meg a cuccot, aztán beszéljük át mi ment át?, illetve mit hogyan kellene javítani, hogy használható legyen

Ok

pont jó hogy laikus vagy

Azert momdom
Milyen formatumban van?
Es mikorra kell es ilyen hosszu?

azt szeretnénk, ha a laikusok is megértenék, és a felületről egyértelműen kiderüljön/érthető legyen mi történik, és mit kell csinálni

Vulagos

adatom.hu
illtve a szabadszavazas.hu login gombra kattintva.

Ok. Atnezem. Valami egyeb tudnivalo?

nem mondok semmit, hogy ne zavarjon meg, az oldalakon lévő infóból mindennek ki kellene derülnie

Rendben, es mar sejtem, mirol van szo.

ok köszi
