### ISSUE TITLE
email change UI tesztelése

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#613]
depends on #409

**Comment by magwas** [comment]
email_change

DECORATOR.interfaceFunc('/v1/emailchange', methods=['POST'], formClass=EmailChangeForm, checkLoginFunction=CONTROLLER.jsonErrorIfNotLoggedIn)

confirm_email_change

DECORATOR.interfaceFunc('/v1/confirmemailchange', methods=['POST'], formClass=ConfirmEmailChangeForm)

class EmailChangeForm(CSRFForm):
    newemail = TextField('newemail', emailValidator)

class CSRFForm(Form):
    csrf_token = TextField('csrf_token', validators = csrfValidator)

class ConfirmEmailChangeForm(Form):
    confirm = BooleanField('confirm')
    secret = TextField('secret', secretValidator)

**Comment by Claymanus** [comment]
Kénytelen vagyok blokkedbe tenni, mert nem működnek a levelek

**Comment by Claymanus** [comment]
blokked #658

**Comment by magwas** [comment]
végig kell tesztelni

**Comment by magwas** [comment]
függ a #653-tól

**Comment by magwas** [comment]
az sso.edemokraciagep.org-on tesztelhető. Az adatom.hu-n a gettext-es javításra várok a deploy-al. @Claymanus

**Comment by krosza** [comment]
gyors teszt eredmények:
1. mentés gomb után egy üres "Szerver üzenet"  felugró  ablak jön
2. a régi email címre  valahogy furcsán jön levél: olyan mintha az egyik része egy előző üzenet szövege lenne, a vége ahol a link van külön kell kattintani, hogy elő jöjjön
3. a vissza térő ablakban nyelvtani hibás szöveg: Email cím cseréje
Az email címed megváltoztatását **kedzdemén**yezted. A "Cserélem" gombra kattintva véglegesítjuk az új email **címidet: **charlie@noba.hu
4. ez talán még nem a végleges üzenet
"Üzi
{"message": "email address changed"}"
5 egy ablakból a végére 3 lesz, ez elég zavaró
 -az " Email cím cseréje ablaknak mindenképpen záródnia kellene 
- az email cím megerősítésekor és két ablak marad nyitva, nem jó
6. a régi emailcímre jövő 2. levélben megszólításnál a régi emailcim van helyesen , de az új címre megy etz a levél is
6. a levél szövegeket is változtatni kell, mert ha az email cím volt a felhasználó azonosító akkor akkor az már nem jó a továbbiakaban
7. az új email címre biztonsági okból nem küldeném a régit, sem a megszólításban, sem külön a szövegben, ha nem fake user akkor ő ugyis tudja a régi címét

**Comment by krosza** [comment]
6. A megszólításnál minden "Kedves  emai"l cím jobb lenne ha az lenne ahova az email megy

**Comment by krosza** [comment]
Fiókom/Adataim     Az igazolások  kiállító cseréjénél a Titkós Kód nál nem cserélném a kiállítót az új email címre mert ez nem igaz, a kiállító a régi email cím volt

**Comment by krosza** [comment]
A régi email cím helyett a 3. email az újra jön

**Comment by krosza** [comment]
a levelek e "-al kezdődnek külön bekezdésben,
miért?

**Comment by Claymanus** [comment]
gettext done @magwas

**Comment by krosza** [comment]
Az új email címre küldött 2. levél, amely az email ellenőrzést csinálja

-vagy elhagyható ( azt hiszem erről beszéltünk) és akkor kiegészítem  a
csere megerősítéséhez felugró ablakban a szöveget, azzal, hogy csinálja meg
az email check-et az új email címre jött levél linkjáével

 -vagy más szöveg kell hozzá,mert most a reg utáni levéll jön, szóljatok
melyiket  írjam

**Comment by magwas** [comment]
Kiment élesbe, lehet ott is tesztelni.

**Comment by magwas** [comment]
Elvileg elhagyjuk az emailcímellenőrzést, ha az új címről kattint.
