### ISSUE TITLE
javascript synkron módon működjön

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#614]

**Comment by Claymanus** [comment]
http://www.html5rocks.com/en/tutorials/es6/promises/

**Comment by Claymanus** [comment]
IE nem támogatja a Promise objektumot

**Comment by magwas** [comment]
https://github.com/stefanpenner/es6-promise

**Comment by Claymanus** [comment]
igen és a kérdés most az, hogy implmentáljunk-e egy új amúgy jó kis funkcionalitásban és szopjunk a kompatibilitásal, vagy örüljönk, hogy működik úgy ahogy most van.
A megoldást valahol a kettő között látom: egy saját promise objektum, ami persze csak anyit tud, amennyi nekünk kell belőle.
