### ISSUE TITLE
külön login . hiba ??? regisztrálásnál

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#617]
mindent megpróbáltam  de az alábbit kaptam:
a link: https://sso.edemokraciagep.org/login.html?next=https%3A%2F%2Fsso.edemokraciagep.org%2Fada%2Fv1%2Foauth2%2Fauth%3Fresponse_type%3Dcode%26client_id%3D3d56a1bf-75fe-4d0a-aa4b-dc01c116ad25%26redirect_uri%3Dhttps%253A%252F%252Fszabadszavazas.hu%252Fsso_callback%253FSSO_action%253Dlogin%2526_wpnonce%253D4f4d38d96a%2526need%253Dhashgiven,emailverification%2526wp_redirect%253D%252F

![uploads/c41f8c36-26e6-4c2d-90cb-45a550a53495/külön reg 2.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc41f8c36-26e6-4c2d-90cb-45a550a53495%2Fk%C3%BCl%C3%B6n+reg+2.JPG)

**Comment by Claymanus** [comment]
mit kell nézni? Az üres hibaüzenet gettext hiba
