### ISSUE TITLE
gettext nem kap stringet

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#618]
be vagyok jelentkezve , el  akarom készíteni a hash-t beírom ott, kattintok  . hiba jön, azután ha rákattintok hogy elkészítem magam és visszamegyek a hash be van írva a mezőbe, nem lehethogy a gomb el van drótozva?

![uploads/66d37fa0-9cfa-4a76-964a-2d0c529cb748/login hash készítés.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F66d37fa0-9cfa-4a76-964a-2d0c529cb748%2Flogin+hash+k%C3%A9sz%C3%ADt%C3%A9s.JPG)

**Comment by Claymanus** [comment]
nem tudom reprodukálni
