### ISSUE TITLE
adatom.hu hash csere/megadás

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#619]
1)    ha már egy létező hash-t adok meg ez a hiba jel jön :

![uploads/cfb3c760-5d6f-4494-afb2-a0295ab1d45b/adatomhu hash csere.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcfb3c760-5d6f-4494-afb2-a0295ab1d45b%2Fadatomhu+hash+csere.JPG)

ezt a hiba üzenetet  jön

**Comment by Claymanus** [comment]
gettext hiba: ha a string túl hosszú akkor több sorba tördeli a deploy script a po-ban, ez viszont nem tetszik a js gettextnek...
