### ISSUE TITLE
adatom.hu  hash ütközést nem detektálja

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#621]
ez egyik user nek van magyar ig.sa krosza@gmail.com,
mégis megengedi, hogy a másik user charlie@noba.hu,  mentse az ő hash-t, hibaüzenet nélkül

erre pedig van hiba üzenet:
#: src/pdoauth/Messages.py:26 src/pdoauth/Messages.py:27
msgid "another user is using your hash"
msgstr ""
"Egy másik Felhasználó is megadta ezt a Titkos kódot. Amennyiben nem a saját "
"adataidat használtad töröld ezt a Titkos Kódot. Ha a Titkos Kód a te "
"adataidból készült, akkor haladéktalanul kezdeményezd a tanúsításodat.Ezzel "
"megakadályozod, hogy  visszaéljenek az adataiddal."

**Comment by magwas** [comment]
nem tudtam reprodukálni. a charlie@noba.hu felhasználónak nincs hash megadva az adatbázisban.
több infó kéne.

**Comment by krosza** [comment]
most jobb mert van hiba üzenet, csak kicsit rossz, Gyuri szerint azért mert túl hosszú az üzenet

amikor menteni akarom a hash-t ami ugyanaz mint ami már bent van a krosza-nél a ez hiba jön: 
![hash utkozes hiba uzenet](https://cloud.githubusercontent.com/assets/12797314/14043231/391f631a-f282-11e5-9760-2ca418e91c5b.JPG)

**Comment by krosza** [comment]
a hash: 15811090062 erdeianna
