### ISSUE TITLE
regisztrációkor figyelmeztetés, hogy vissza kell igazolnod az emailt

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#622]
hová rakjuk?

**Comment by krosza** [comment]
Mit szólnátok, ahhoz, hogy a reg befejezésekor mielőtt a fiókom oldal aktív lenne felugrana egy figyelmeztető ablak szöveggel :
" A regisztráció során megadott email fiókodat igazolnod kell azzal, hogy a számodra küldött levélben megadott linkre kattintasz. Amennyiben a bejövő levelek között nem találod levelünket kérjük ellenőrizd a spam (levélszemét) levelek között is. A visszaigazolás hiányában a fiókodat a regisztrációtól számított egy héten belül automatikusan töröljük. Megértésedet köszönjük."
ide kellene egy "Bezár" gomb

én ezt mindaddig kiraknám amíg nincs meg az email checkje és rákattint a fiókom menüre

**Comment by Claymanus** [comment]
ok. felvettem a mostani sprinbe
