### ISSUE TITLE
static oldalak page title szövegek

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#625]
Ezek azok a szövegek, amik a böngésző címsorában jelennek meg.
Károly találd ki plíz, én meg majd jól belerakom

**Comment by krosza** [comment]
nekem ez a négy jön , ezekre gondolsz?

https://adatom.hu/index.html
https://adatom.hu/fiokom.html
https://adatom.hu/about_us.html
https://adatom.hu/user_howto.html

**Comment by Claymanus** [comment]
igen

**Comment by krosza** [comment]
szerintem:
https://adatom.hu/Fooldal
https://adatom.hu/Fiokom
https://adatom.hu/Rolunk
https://adatom.hu/Hogyan_mukodik

A fő menüben a Home-t mindenképpen cserélném "Főoldal"-ra
