### ISSUE TITLE
bejelentkezési hiba üzenet

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#629]
![uploads/59d269ee-4ed4-45cb-b4af-962e03e67d2c/bejelentkezés hiba üzenet.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F59d269ee-4ed4-45cb-b4af-962e03e67d2c%2Fbejelentkez%C3%A9s+hiba+%C3%BCzenet.JPG)

ilyet csak regnél szabadna kapni, de akkor is csak egy nyelven

**Comment by Claymanus** [comment]
a hiba ok a #628 volt. fixed
