### ISSUE TITLE
fb login eltört

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#631]
ha a v1/login secret-ben kapja a tokent, akkor a password validation hibaüzeneteit adja a szerver
ha password-ben megy a token, akkor meg 500 a válasz

**Comment by magwas** [comment]
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544] mod_wsgi (pid=4009): Exception occurred processing WSGI script '/usr/local/PDOauth/wsgi/app.wsgi'., referer: https
://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544] Traceback (most recent call last):, referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__, referer: https://sso.edemokr
aciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     return self.wsgi_app(environ, start_response), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app, referer: https://sso.edemokr
aciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     response = self.make_response(self.handle_exception(e)), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception, referer: https://sso
.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     reraise(exc_type, exc_value, tb), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app, referer: https://sso.edemokr
aciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     response = self.full_dispatch_request(), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request, referer: https:
//sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     rv = self.handle_user_exception(e), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception, referer: https:
//sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     reraise(exc_type, exc_value, tb), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request, referer: https:
//sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     rv = self.dispatch_request(), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request, referer: https://sso
.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     return self.view_functions[rule.endpoint](**req.view_args), referer: https://sso.edemokraciagep.org/fiokom.htm
l
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/PDOauth/src/pdoauth/Decorators.py", line 45, in validated, referer: https://sso.edemokraciagep.
org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     return self.runInterfaceFunc(func, args, kwargs, formClass, status, checkLoginFunction), referer: https://sso.
edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/PDOauth/src/pdoauth/Decorators.py", line 22, in runInterfaceFunc, referer: https://sso.edemokra
ciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     resp = func(*args, **kwargs), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/PDOauth/src/pdoauth/main.py", line 44, in login, referer: https://sso.edemokraciagep.org/fiokom
.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     return CONTROLLER.doLogin(form), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/PDOauth/src/pdoauth/Controller.py", line 74, in doLogin, referer: https://sso.edemokraciagep.or
g/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     return self.facebookLogin(form), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/PDOauth/src/pdoauth/LoginHandling.py", line 46, in facebookLogin, referer: https://sso.edemokra
ciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     self.checkIdAgainstFacebookMe(form), referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]   File "/usr/local/PDOauth/src/pdoauth/LoginHandling.py", line 37, in checkIdAgainstFacebookMe, referer: https://s
so.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544]     code = form.secret.data, referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache2[4009]: [:error] [pid 4009:tid 139971188922112] [client 212.48.246.224:51544] AttributeError: 'LoginForm' object has no attribute 'secret', referer: https://sso.edemokraciagep.org/fiokom.html
Mar 24 20:22:01 sso apache[4007]: sso.edemokraciagep.org:443 212.48.246.224 - - [24/Mar/2016:20:22:01 +0100] "POST /ada/v1/login HTTP/1.1" 500 1006 "https://sso.edemokraciagep.org/fiokom.html" "Mozilla/5.0 (Windows NT 6
.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
