### ISSUE TITLE
fb reg élesen törött?

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#632]
"regisztrálni akartam fb-al de nem történt semmi. jelszóval ment de mikor a végén nyomtam a gombot nem volt semmi üzenet, hogy sikerült nézd meg a leveleidet, de mikor megint megnyomtam akkor közölte, hogy van már ilyen user"

**Comment by magwas** [comment]
nem jön email a facebooktól, ez az eset nincs lekezelve a js-ben.
Külön kommit legyen, hogy a deploymentbe be tudjam cherrypickelni.

**Comment by Claymanus** [comment]
mehet ki
