### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#636]
Sziasztok,

tök klassz, gratula!
- az h fogok kapni email-t amit vissza kell igazolnom, az világos a szövegből? nekem valahogy nem jött le..
- regisztráció után, belépéskor a kod helyén fölöslegesen vannak csillagok, ez engem megzavart. sztem ki kéne szedni őket
- angol nyelvü gombot kiszedni

most ennyi, még nézem,

a.

**Comment by Claymanus** [comment]
- #622
