### ISSUE TITLE
facebook reg még mindig nem megy

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#637]
jelszóerősségi problémák vannak (adatom.hu)

**Comment by Claymanus** [comment]
fb reg contextusban nem értelmezhető a jelszóerősség probléma. Fejtsd ki plíz

**Comment by magwas** [comment]
Nekem ment a regisztráció teszt userrel. A jelszóerősség probléma úgy értelmezhető, hogy az fb regisztrációnál a password mezőbe a facebook-os access token vagy micsoda kerül.

**Comment by Claymanus** [comment]
fb regisztrációnál secret mező van.

**Comment by magwas** [comment]
A usernél az fb alkalmazásai között nem szerepel az ada, és ez van a javascript console-on:
initcallback 403
fb.js:102 fb_login
fb.js:79 Object {authResponse: undefined, status: "not_authorized"}
fb.js:83 not_authorised
