### ISSUE TITLE
jelszavas regisztráláskor nincs üzenet a sikeres regisztrálásról

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#638]
adatom.hu

**Comment by Claymanus** [comment]
mert a testszerveren van?

**Comment by magwas** [comment]
Ott nem néztem.
Tulajdonképpen az történik, hogy átvált a fiók nézetébe, de nem a lap tetején, ezért pont az infó nem látszik. Meg egy üzenet, ami arról, szól, hogy regisztráltunk, beléptél, nézd meg a mailboxod lehet hogy nem lenne hülyeség.

**Comment by Claymanus** [comment]
ok #622

**Comment by magwas** [comment]
SSL-el próbáltam regisztrálni. Nem ment. Váltottam jelszavasra. Az már ment, de nem váltott az oldal a fiók nézetbe. Valami keverés az ssl-specifikus redirektek miatt?

**Comment by Claymanus** [comment]
regisztráció után frissítsük a ui-t.
amúgy nekem ff-ben megy az SSL regisztráció, csak nem frissül a UI, mer nem tudom detektálni a cert mentését. Tettem egy üzenetet a registration felületre, hogy frissítse a user az oldalt, he nem frissül automatice
