### ISSUE TITLE
új üzenetek a po file-ban, levélszövegek

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#653]
A po file-ban új üzenetek vannak. Ezen kívül:
Az alábbi három levél tárgyát és szövegét kellene megírni:
- emailcím változtatás kezdeményezésekor a régi email címre menő levél
  - paraméterek: {0.name}, {0.secret}, {0.expiry}
- emailcím változtatás kezdeményezésekor az új email címre menő levél
  - paraméterek: {0.name}, {0.secret}, {0.expiry}
- emailcím változtatás bekövetkezésekor a régi emailcímre menő levél
  - paraméterek: {0.name}

**Comment by magwas** [comment]
CHANGE_EMAIL_DONE_EMAIL_SUBJECT = "warnemail address change has been requested"
    CHANGE_EMAIL_DONE_EMAIL_BODY_TEXT = "warnDear {0.name}"
    CHANGE_EMAIL_DONE_EMAIL_BODY_HTML = "warnhtml {0.name}"
    CHANGE_EMAIL_OLD_EMAIL_SUBJECT = "oldemail address change has been requested"
    CHANGE_EMAIL_OLD_EMAIL_BODY_TEXT = "oldDear {0.name}, {0.secret}, {0.expiry}"
    CHANGE_EMAIL_OLD_EMAIL_BODY_HTML = "oldhtml {0.name}, {0.secret}, {0.expiry}"
    CHANGE_EMAIL_NEW_EMAIL_SUBJECT = "new email address change has been requested"
    CHANGE_EMAIL_NEW_EMAIL_BODY_TEXT = "newDear {0.name}, {0.secret}, {0.expiry}"
    CHANGE_EMAIL_NEW_EMAIL_BODY_HTML = "newhtml {0.name}, {0.secret}, {0.expiry}"

**Comment by krosza** [comment]
A régi email címre menő első  levélben a secret egy link gondolom, mit fog csinálni a rendszer  ha rákattint?

**Comment by krosza** [comment]
Amennyiben a régi email címet  Felhasználó azonosítóként is használta az ügyfél akkor az továbbra is az marad vagy az is cserélődik automatikusan?

**Comment by krosza** [comment]
nem emlékszem, pontosan mi a folyamat, ha más mit amit feltételeztem majd javítom 

CHANGE_EMAIL_OLD_EMAIL_SUBJECT = "Email cím változtatás"

Kedves {0.name}!

Ezt a levelet azért kaptad mert az ADA oldalán kezdeményezted az email címed megváltoztatását

Amennyiben az alábbi linkre kattintasz, akkor az ADA rendszerében a továbbiakban  ezt az  email címedet nem fogjuk tárolni  és az ADA rendszeréből a továbbiakban csak az általad megadott új  email címedre :  {NEW_EMAIL } küldünk értesítéseket.

 Amennyiben a régi email címedet  Felhasználó azonosítóként is használtad  akkor az továbbra is megmarad Felhasználó azonosítóként, de értesítéseket ekkor is csak az új email címedre kapsz  tőlünk  a továbbiakban.

Kattintandó link: {0.secret}

A linket a következő időpontig használhatod fel:   {0.expiry}


**Amennyiben nem te kezdeményezted a változtatást  akkor feltétlen  írj nekünk az info@adatom.hu  címre.**


Üdvözlettel:

Az ADA csapata

 


CHANGE_EMAIL_NEW_EMAIL_SUBJECT = " Email cím változtatás "

Kedves {0.name}!

Ezt a levelet azért kaptad mert az ADA oldalán kezdeményezted az email címed megváltoztatását Amennyiben az alábbi linkre kattintasz, akkor az ADA rendszerében a továbbiakban  csak  ezt az  (új) email címedet fogjuk tárolni.

 Amennyiben a régi email címedet  Felhasználó azonosítóként is használtad  akkor az továbbra is megmarad Felhasználó azonosítóként, de értesítéseket ekkor is csak az új email címedre kapsz tőlünk  a továbbiakban.

Kattintandó link: {0.secret}

A linket a következő időpontig használhatod fel:   {0.expiry}


**Amennyiben nem te kezdeményezted a változtatást  akkor hagyd figyelmen kívül ezt a levelet!**

 

Üdvözlettel:

Az ADA csapata

CHANGE_EMAIL_DONE_EMAIL_SUBJECT = "Email cím sikeres cseréje"

Kedves {0.name}!

Ezt a levelet azért kaptad mert az ADA oldalán kezdeményezted az email címed megváltoztatását.  Az ADA rendszerében tárolt email címedet kicseréltük  erre: {NEW_EMAIL }

Amennyiben a régi   email címedet  Felhasználó azonosítóként is használtad  akkor az továbbra is megmarad Felhasználó azonosítóként, de értesítéseket ekkor is csak az új email címedre kapsz  tőlünk  a továbbiakban.


**Amennyiben nem te kezdeményezted a változtatást  akkor feltétlen  írj nekünk az info@adatom.hu  **címre.


Üdvözlettel:

Az ADA csapata

**Comment by magwas** [comment]
Írjam be a konfigba
