### ISSUE TITLE
fiókom/beállítások/emailcím  nem jó ikon van kint defaultban

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#669]
itt  https://sso.edemokraciagep.org/fiokom.html
az csere ikon helyet a mentés ikon  jön alapból, amire kattintva nyilván a nem idevaló hiba üzenet jelenik meg ti. ilyen fiók már van...

ha még nem kész az email csere akkor maradjon a régi üzenet ami az adatom.hu-n kint van most  "ez a funkció még nem működik"

**Comment by Claymanus** [comment]
1. milyen ikon legyen? https://fortawesome.github.io/Font-Awesome/icons/
2. Nálam a hibaüzenet pont azt írja, hogy ilyen fiók már van.
3. Ez a funkció működik, csak a hibaüzeneteket még nem lektorálta senki.

**Comment by krosza** [comment]
az írós ikonnak kellene kint lenni, amire kattintva lehet cserélni az email
címet, most nem működik még a csere úgy látom, a hiba üzenet jó a mostani
ikonhoz, mert ha valaki menteni akarja az új címet és az más a rendszerben
van akkor tényleg ennek kell jönni.
