### ISSUE TITLE
Linkelhetővé tenni a  howto-k fejezeteit

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#678]

**Comment by Claymanus** [comment]
user_howto.html
- Regisztráció -> #regisztracio
- TITKOS KÓD -> #titkos_kod
- Igazolások -> #igazolasok
- Tanúsítás -> #tanusitas
- Alkalmazások ->  #alkalmazasok
- Az adataid kezelése -> #adatkezeles

**Comment by magwas** [comment]
eltakarja az elejét a header

**Comment by Claymanus** [comment]
ezt tegyük done-ba, veszek fel egy másik jegyet akontentet eltakaró fejlécről.
