### ISSUE TITLE
hova kell linkelni a NAIH 

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#694]
nyilvántartásba vételről szóló határozatot

**Comment by krosza** [comment]
A határozat a szám alapján hozzáférhető,
praktikusan sztem a Gibook adatkezelési tájékoztató, határozat szám lehetne
maga a link

**Comment by Claymanus** [comment]
naszóval akkor: feltettem a staticba a határozatot lsd #673. Ez a linkje: /docs/NAIH-nyilvantartasbavetel-123690.pdf. A kérdés, hogy a weblap mely részein kell ennek a linknek megjelennie.

**Comment by krosza** [comment]
egy olyan link kellene amit be tudok rakni a gitbookba

**Comment by magwas** [comment]
https://adatom.hu/docs/NAIH-nyilvantartasbavetel-123690.pdf

**Comment by krosza** [comment]
kösz
