### ISSUE TITLE
emil tesztelhetőség

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#713]
- e2e tesztuser tesztelek@adatom.hu
- a levelei egy file-ba érkeznek
- amik elérhetőek a static kontextusban

**Comment by magwas** [comment]
egy könyvtár, amiben benne van a legutoljára beérkezett levél, és a konfig belinkelve
látszódjon https-en.

**Comment by magwas** [comment]
https://sso.edemokraciagep.org/mailbox
emailcím: tesztelek@sso.edemokraciagep.org

**Comment by magwas** [comment]
gyuri, így jó lesz?

**Comment by Claymanus** [comment]
yep
