### ISSUE TITLE
lóvé átutalása

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#720]

**Comment by krosza** [comment]
Csaba nem jelzett nekem vissza, ezért sztem utaljunk 50-et, ha azt mondja majd később hogy  ok akkor elrendezzünk magunk között.
 A számlaszám lent, a közleménybe írjátok:
KDE  Alapítvány  alapítói hozzájárulás



CIB Bank Zrt.

10702301-66350347-51900001

**Comment by krosza** [comment]
rendben
