### ISSUE TITLE
fb regisztráció nem működik

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#726]

**Comment by magwas** [comment]
Nekem működik a teszt rendszeren, teszt is van hozzá.
Teszteld meg kérlek, és ha nem megy, akkor ki kellene találni, hogy mi az a csillagállás, amikor nem megy.

**Comment by krosza** [comment]
Az lehet hogy csak akkor tudok belépni  FB-vel ha azon keresztül regisztráltam?

**Comment by krosza** [comment]
csak firefox - esetleg beállítási- problémának tűnik, so
vehetjük késznek

**Comment by magwas** [comment]
Ha beállítási probléma,akkor dokumentálni kéne a helyes beállításokat,
vagy azt hogy milyen csillagállásnál nemtud működni.

**Comment by krosza** [comment]
Firefox.: Do not use " Tracking Protection"  
FB belépéshez kapcsold ki a "Tracking Protection"-t

Hová dokumentáljunk ilyeneket?

**Comment by Claymanus** [comment]
Szrintem a faq-ba

**Comment by Claymanus** [comment]
Szerintem a faq-ba




2016 Szeptember 28, Szerda 09:30 CEST dátummal, krosza <notifications@github.com> ezt írta:
 
Firefox.: Do not use " Tracking Protection"

FB belépéshez kapcsold ki a "Tracking Protection"-t
Hová dokumentáljunk ilyeneket?

**Comment by krosza** [comment]
Hova rakjuk a FAQ -ot?
