### ISSUE TITLE
Boriék a tanusítók listájára

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#730]

**Comment by magwas** [comment]
@krosza lszi ird be az adatokat ide

**Comment by krosza** [comment]
Lang A.
Bp, Szentendre.
lang.andras@gmail.com

Takács B.
Bp., Nagymaros 
takacsbori@gmail.com
Bori kérné hogy legyen egy adás email címe ( takacsbori@adatom.hu)    erre a  célra a gmailes fiókba irányítva
