### ISSUE TITLE
tanúsító ikon fiokom felület, cserélni kellene az újra

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#735]
![uploads/0216a923-0ef9-4aad-8d3d-3e0ef5ec4d61/hiba tanúsító ikon.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0216a923-0ef9-4aad-8d3d-3e0ef5ec4d61%2Fhiba+tan%C3%BAs%C3%ADt%C3%B3+ikon.JPG)

**Comment by Claymanus** [comment]
mi az új?

**Comment by krosza** [comment]
ami a főoldalon van, amit már cseréltél
