### ISSUE TITLE
hash elkészítésekor nincs hashgiven

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#737]

**Comment by magwas** [comment]
Készült end-to-end teszt. Ha van hash, akkor van hashgiven is.

**Comment by magwas** [comment]
tesztelni kéne az sso.edemokraciagep.org-on.

**Comment by krosza** [comment]
A hash  folyamat ok, viszont van egy UI probléma:
ha van hash akkor két ikon  billentyű van írás és törlés, bármelyikre kattintok törli a hasht és az összes igazolást!!!!!!

 az irás esetében ugyan feljön: Ha megváltoztatod a Titkos Kódodat, az összes eddigi igazolásod elvész!
de ez már késő, szóval előbb jön a pofon és utána a figyelmeztetés, ezt így nem akartuk:

megoldási jav:  a) legyen mindig kint a szöveg b) normálisabb: kattintok felugrik egy tábla tényleg akarod-e , mert elvész.... stb

**Comment by krosza** [comment]
egyébként nem tudtam eddig az eredeti hibát produkálni

**Comment by magwas** [comment]
Akkor ezt lezárom, a másik probléma pedig a #772 jegyen van
