### ISSUE TITLE
hash ütközés nincs email, és figyelmeztetés, csak törlés

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#744]
sso, azt a user törli aki uo. hasht ad meg mint ami már a rendszerben van, senki sem kap mailt

**Comment by krosza** [comment]
megerősítve,

**Comment by krosza** [comment]
ezzel foglalkoztál már, nekem még mindig nem jön mail

**Comment by krosza** [comment]
megadom az ütköző hash-t, próbálom menteni, de úgy maradok látszólag semmi sem történik 
utána kijelentkezek,  be tudok újra jelentkezni,
emailejk nem jönnek

**Comment by krosza** [comment]
teszt eredmény:  a) két nem magyar esete
ok:
- user figyelmeztetés felugró ablak  
hibák:
-ilyenkor is törli a user-t aki megadta az ütköző hash-t
-az ütközést okozó user kapja a mailt-t és nem az akit eltaláltak
- email szöveg rossz:
"Dear szabo.karoly@bsfuzfo.hu,
Someone have tried to register with your hash with adatom.
Sincerely,
The Test machine "

 a jó megvan valahol csak nem találom

**Comment by magwas** [comment]
a tanusított usernek menjen az email.

**Comment by krosza** [comment]
a 781 hibajegybe írtam a levélszövegeket

**Comment by krosza** [comment]
sso teszt:


1.  tanúsított felhasználó kontra új felhasználó

 javult a helyzet, 
most már jó címre jön a levél csak 4 db egymás után  és angol szöveg, hová lehet berakni a magyart amit a 781-es jegybe írtam?

**Comment by krosza** [comment]
2. két nem tanúsított felhasználó esetén
a másodikat törli a rendszer, ezt itt nem kellene, mert így nem is lehet őt tanúsítani, és a tanúsító sem tud semmit tenni ez ügyben
ez egyébként az 1 esetben is probléma, de reméljük, hogy ilyen nem fog előfordulni,  képernyőn megjelenő üzenetben ezért inkább azt kellene írni, hogy írj  levelet a ... címre az üzenetben

**Comment by krosza** [comment]
3. két nem tanúsított felhasználó esetén
felhasználó véletlenül a regisztráció során ütköző hash-t adott meg, az érintett megkapta a figyelmeztető levelet, ez ok, viszont mikor a felhasználó egy másik A HELYES, hash-el  tanúsításra került az érintettet mégis csak törölte a rendszer, pedig nem kellett volna

**Comment by magwas** [comment]
Törölni csak az alábbi két esetben:
1. user olyan hash-t ad meg, amire már van magyar igazolás (forduljon hozzánk, ha mégis az a hash-e, mert valakit)
2. magyar igazolás kiadásakor az ugyanolyan hash-ű usereket

**Comment by magwas** [comment]
Két tanúsítatlan felhasználónál csak figyelmeztetés és email, nem törlünk.

**Comment by magwas** [comment]
@krosza itt a modell: http://adadocs.demokracia.rulez.org/ADA/#b4440d6d-573a-4a3b-9771-e71a9d5453d8

**Comment by rozsar** [comment]
Mag-ra var....

**Comment by magwas** [comment]
lásd #926
