### ISSUE TITLE
tanúsításnál, rossz hibaüzenet a hash megadásakor

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#745]
a user által elmentett és a tanúsítás során megadott hash különbözik,
a hibaüzenet: ld azt modje nincs hash neki holott azt kellene mondani, hogy a két hash nem egyezik meg

![uploads/170cd71c-62bb-4ab3-b55d-f02f4a27e84b/rossz hiba üzenet.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F170cd71c-62bb-4ab3-b55d-f02f4a27e84b%2Frossz+hiba+%C3%BCzenet.JPG)

**Comment by magwas** [comment]
waiting for #759
