### ISSUE TITLE
sso, titkos kód   elkészül, de nem  engedi elmenteni 

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#753]
firefox böngésző v46.01

**Comment by krosza** [comment]
az sso-on a hiba fennáll továbbra is
az adatom.hu, az alábbi hiba üzenetet küldi hash előállításakor
![uploads/db044334-fa0c-452a-b298-d9a175e5bf4c/hash hiba adatom.hu.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdb044334-fa0c-452a-b298-d9a175e5bf4c%2Fhash+hiba+adatom.hu.JPG)

**Comment by Claymanus** [comment]
@krosza ez a hiba még él?

**Comment by krosza** [comment]
Igen, mikor hash utkozes van ket tanusitatlan user kozott

**Comment by Claymanus** [comment]
nem tom reprodukálni ezt a hibát, majd mutasd meg lécci kedden, hogyan csinálod

**Comment by krosza** [comment]
nem tanúsított hash ütközéskor probáld
