### ISSUE TITLE
UI parametrized i18n

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#759]
The server can give back two kinds of i18nable objects:

a) a simple string.
  This should be directly looked up in the po and displayed.
b) a list of strings in the form [fmt, param, param...]
  Example: ["assurance {1} is issued to {2}", "magyar", "lo@bela.hu"]
 In this case the fmt string should be looked up in the po. The resulting string will contain markers (see the example above) for the positional parameters. After that the result should be equivalent to pythons fmt.format(param, param...). For the above example, if the po have given back "Kiadtuk a {1}tanusítást {2} számára", then the resulting string should be "Kiadtuk a magyar tanusítást lo@bela.hu számára".

**Comment by Claymanus** [comment]
ezzel akkor mit is kell tenni?
