### ISSUE TITLE
alkalmazás útmutatókérdések

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#761]
Ez alapján: https://edemo.gitbooks.io/utmutato-alkalmazasok-szamara/content/chapter2.html

**Comment by krosza** [comment]
a kérdéseket felraktam ide: 
https://docs.google.com/document/d/1hxOujXp4b5auYNiLUTs4d1BiianAWqXXzV_rW8LkFdQ/edit?usp=sharing

**Comment by magwas** [comment]
be kell integráljam

**Comment by magwas** [comment]
ÁtrakomGyurira, mert ezeket a kérdéseket ő tudja megválaszolni gyorsan.

**Comment by Claymanus** [comment]
Beleírtam a wp-s kérdésekre a válaszomat

**Comment by krosza** [comment]
done
