### ISSUE TITLE
service provider login iframe-ben nem megy néhány platformon

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#773]

**Comment by Claymanus** [comment]
Legközelebb tolj ide egy linket. mondjuk ezt. https://elovalasztok.oldal.cloud/component/users/?view=login

A böngésző logja:
Mixed Content: The page at 'https://elovalasztok.oldal.cloud/component/users/?view=login' was loaded over HTTPS, but requested an insecure resource 'http://li-de.tk/ssologin/index.php?redi=aHR0cDovL2Vsb3ZhbGFzenRvay5vbGRhbC5jbG91ZA'. This request has been blocked; the content must be served over HTTPS.

érdemes volna a protokollokat összeegyeztetni az iframe-ben
