### ISSUE TITLE
igazolás fordítás  hibák

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#776]
sso-ban explorer, estében angol jelenik meg, fire fox és chrome  részben 
mellékelve

![uploads/8cefbdee-4370-4649-9217-31fcf4ddc2d7/fordítas hiba.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8cefbdee-4370-4649-9217-31fcf4ddc2d7%2Fford%C3%ADtas+hiba.JPG)

**Comment by Claymanus** [comment]
Szerintem ez megjavult. @krosza lécci nézd meg IE-ben
