### ISSUE TITLE
tanusítók listája jsonba

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#780]

**Comment by Claymanus** [comment]
json structure:

{
	"assurers": [
		{
			"name":"Mekk Elek",
			"email":"mekkelek@adatom.hu",
			"districts":["Budapest","Velence","VĂˇcrĂˇtĂłt"],
			"assurances":	[
				{
					"assurance":"magyar",
					"expires":"never"
				}
			],
			"availability":"yes"
		}
	]
}

the record will not be displayed if availability is false

/static/assurers.json contains real data (gitignored)
/static/assurers.exmpl contains this stucture
