### ISSUE TITLE
a content provider login oldalt a regisztrációs tabbal is lehessen hívni

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#783]

**Comment by Claymanus** [comment]
?section=registration works only if user is not logged in

**Comment by magwas** [comment]
nincs rá teszt

**Comment by Claymanus** [comment]
itt a teszt: https://sso.edemokraciagep.org/login.html?section=registration&next=https%3A%2F%2Fsso.edemokraciagep.org%2Fada%2Fv1%2Foauth2%2Fauth%3Fresponse_type%3Dcode%26client_id%3D2e5f99ce-3748-48ad-972d-fd5efd339e04%26redirect_uri%3Dhttps%3A%252F%252Fpatyicivil.hu%252Fwp-admin%252Fadmin-ajax.php%253Faction%3DeDemoSSO_login%26_wpnonce%3D02b3e39384
