### ISSUE TITLE
választókerületi assurance kiadásának szabályai

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#808]

**Comment by krosza** [comment]
itt van a módosított Felhasználási Feltételek
https://www.gitbook.com/book/edemo/ada-felhasznalasi-feltetelek/edit#/edit/ADA-Felhaszn%C3%A1l%C3%A1si-felt%C3%A9telek-1.0/README.md?_k=3msgto
itt pedig a módosított Tanúsítási Szabályzat
https://www.gitbook.com/book/edemo/ada-tanusitasi-szabalyzat/edit#/edit/ADA-Tan%C3%BAs%C3%ADt%C3%A1si-Szab%C3%A1lyzat-1.0/README.md?_k=hllvj6

**Comment by magwas** [comment]
nem látom az új módosításokat

**Comment by krosza** [comment]
Gitbook branch, azt nem latod?

**Comment by magwas** [comment]
typo-k

**Comment by Claymanus** [comment]
Az igazolások szekcióba nem került be. Ez most direkt, vagy véletlen?
https://edemo.gitbooks.io/ada-tanusitasi-szabalyzat/content/iii_igazolasok.html

**Comment by krosza** [comment]
direkt nem raktam ide az egyéb zárójeles részében utaltam rá, de nem
kardinális, ha szükséges berakhatjuk, de alapból ezt egy tanúsítónak nem
kell tudni

**Comment by krosza** [comment]
a jelenlegi beállítások szerint az oevk igazolás úgy adható ki ( és ez  vleg igaz bármi egyéb igazolásra is) hogy akkor is újra meg kell adni  a titkos kódhoz szükséges adatokat  ha a felhasználónak van már magyar igazolása, ez egy duble check, és kicsit kellemetlen a fehasználóbnak, kérdés: akarjuk-e így? Az kétségtelen, hogy ennek hiányában a rendszer hekkelhető, mert egyébként a tanúsító  semmilyen más módon nem tudja ellenőrizni az email cím alapján meghatározott  a személy azonosságot.
Ha így marad akkor kiegészítem még a szabályzatot, és a felhasználási feltételeket azzal, hogy  " az igazolás kiadásakor a Tanúsító újra ellenőrzi a felhasználó személyazonosságát azzal, hogy a felhasználó  Titkos Kódját újra előállítja ( a szükséges személyes adatokat a lakcímkártyáról a tanúsítói felületre beírja)."
Mi a véleményetek?
