### ISSUE TITLE
KDE sajtóanyag

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#812]
Legyen egy sajtóanyagunk, amiben egyértelművé tesszük a framework-content dolgot, és fényezzük az adát.

**Comment by magwas** [comment]
a lead legyen max két mondat, bolddal kiemelve, és minden legyen benne, ami fontos.

**Comment by krosza** [comment]
itt az anyag véleményezésre:
https://docs.google.com/document/d/1q6ejJfw4_8wXyx_oT1GaKk0HELQPSOQLPWsDJgSyIgk/edit?usp=sharing
