### ISSUE TITLE
sso ui hiba

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#839]
ld képet
![uploads/801a994d-956a-4ef1-9549-2be7cf38aabe/külalak 1.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F801a994d-956a-4ef1-9549-2be7cf38aabe%2Fk%C3%BClalak+1.JPG)

**Comment by Claymanus** [comment]
ok, de mi a hiba?

**Comment by Claymanus** [comment]
Látom én, Virág elvtárs, hogy valahogy kinéz. Ezt kérték legutóbb, amikor a pártszékházban jártam. Kicsit savanyú, kicsit sárga, de a miénk. Hogyan nézzen ki, hogy Bástya elvtársnak is jó legyen? Fessük be narancssárgára?

**Comment by Claymanus** [comment]
976px alatt ott is összecsúszik

**Comment by Claymanus** [comment]
de amúgy nyilván rendbe kell tenni

**Comment by krosza** [comment]
amit nem értek az sso felület most jó az adatom pedig hibás , ugyanaz a böngésző..

**Comment by Claymanus** [comment]
Gondolom kiment az élesre a rossz verzió, és közben megjavítottam az sso-n. Majd @magwas kiteszi a javítást valamikor.
