### ISSUE TITLE
adatom.hu  probléma

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#842]
a tanúsító felület  elszállt
![uploads/3fa1f82d-c574-4fc4-a222-9190f63832dc/hiba1.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3fa1f82d-c574-4fc4-a222-9190f63832dc%2Fhiba1.JPG)

**Comment by Claymanus** [comment]
@magwas lécci tedd fel az igazi assurer.json-t plíz ;-)

**Comment by krosza** [comment]
a nyitó oldalon a számláló elég furcsákat tud mutatni, ha többször átgörgetünk rajta pl.
![uploads/00a04fde-1acd-4ac7-84c9-b473840f53bf/hiba 2.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F00a04fde-1acd-4ac7-84c9-b473840f53bf%2Fhiba+2.JPG)

**Comment by Claymanus** [comment]
na ugye mondtam, ha egyszer beindul a szekér...  ;-)

**Comment by Claymanus** [comment]
Tedd egy másik jegybe plíz.  Ez amúgy akkor van ha ide görgetsz, és frissíted az oldalt. Ugyanis a számláló elkezd számolni a default értékek alapján, de még nem érkezett meg az adat az adától.
