### ISSUE TITLE
a nyitó oldalon a számláló elég furcsákat tud mutatni, ha többször átgörgetünk rajta pl.

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#845]
![uploads/a9f78d84-0db2-4d96-a77e-dec38c7f8ca3/hiba 2.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa9f78d84-0db2-4d96-a77e-dec38c7f8ca3%2Fhiba+2.JPG)

**Comment by krosza** [comment]
ezt nem lehetne sos megjavítani és kirakni, elég sok jelentkező regisztráló van és ezt mindenki nézegeti, így nagyon gáz

**Comment by Claymanus** [comment]
nézd meg az sso-n hogy jó-e

**Comment by Claymanus** [comment]
van egy másik issu is ebben

**Comment by krosza** [comment]
nekem működik

**Comment by krosza** [comment]
az mi?
