### ISSUE TITLE
facebook login hibaüzenet

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#847]
Ha facebookkal akar a user belépni/regisztrálni, és hiba van, akkor ne a szerver hibaüzenetet kapja (az megtévesztő), hanem egy olyat, amiben benne van, hogy mik kellenek a facebook belépéshez

**Comment by magwas** [comment]
lásd még #803

**Comment by Claymanus** [comment]
az lehet egy policy, hogy ajax hívás előtt mindig data validation-t végzünk. ehhez viszont kellenek nekem a validációs paraméterek.

**Comment by Claymanus** [comment]
ok, egyelőre figyeljük, hogy jön-e userid és access token az fb-től. A client side data validation-ra majd csinálunk egy másik issue-t. ez most nem sürgős
