### ISSUE TITLE
Fiókom /tanúsítás /tanúsító email gomb sos

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#856]
nekem két böngészőben sem tudja a levelező programot megnyitni., ha rá kattintok, vhogy az email címet ki kellene írni, hogy itt ne akadjon el a dolog, pl ha fölémegy megjelenik az emailcím vagy bárhogy

**Comment by magwas** [comment]
legyen vágólapra tevős gomb

**Comment by Claymanus** [comment]
sso-n nézd meg, hogy jó lesz-e így

**Comment by krosza** [comment]
a probléma hogy félrevezető az üzenet ami megjelenik ha az egérrel rámész a
vágólapra "Email cím cserje megtörtént" mit akar ez mondani??? itt
annak kellene megjelenni hogy "A tanúsító email címének másolása"

**Comment by Claymanus** [comment]
valaki elrontja a fordítást, ennek az üzenetnek máshol kellene megjelennie, nézem

**Comment by Claymanus** [comment]
javítva
