### ISSUE TITLE
Giitbook link neve

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#864]
A jobb alsósarokban van egy "Gitbook" link.
Mi lenne, ha annak "ADA dokumentáció" lenne a neve?

**Comment by krosza** [comment]
ok, az ikont is érdemes lecserélni a gibookra

**Comment by Claymanus** [comment]
sajna a fontawesome icon lib még nem tartalmazza a gitbook iconját, használjunk addig valami más doc. szerű icont: talán ezt: http://fontawesome.io/icon/book/
ha ez nem tetszik itt tudsz válogatni: http://fontawesome.io/icons/

**Comment by krosza** [comment]
jó az teljesen, de a github is maradhat...

2017-01-09 10:18 GMT+01:00 György Peng <notifications@github.com>:

**Comment by madcsaba** [comment]
ez az ikon van https://avatars2.githubusercontent.com/u/7111340?v=3&s=400
