### ISSUE TITLE
Kijelentkezés az adából (Ajax, CORS) blokkolva

### ISSUE THREAD

**Issue by Gerviba** [edemo/PDOauth#879]
Cross-origin HTTP request blockolva az ADA /v1/logout interfaceén.

Szerintem ez a kód megoldaná a problémát:
&lt;?php
    header("Access-Control-Allow-Origin: *");
    header("Access-Control-Allow-Credentials: true");
?&gt;

**Comment by Claymanus** [comment]
ez így van jól.
