### ISSUE TITLE
Ability to remove the certificate type of credentials

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#89]
now allowed:
-facebook
-password

**Comment by magwas** [comment]
And what is the request?

**Comment by Claymanus** [comment]
if the credentialType!=(facebook | password) an error message appears

**Comment by Claymanus** [comment]
csrf_token: csrf validation error

**Comment by Claymanus** [comment]
csrf_token bug fixed in https://github.com/Claymanus/PDOauth/commit/786e1bcf6e8db4f84968949dc0cba6655a6ec6e3
