### ISSUE TITLE
Mit láthat a user 

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#893]
van egy ilyen szabályunk a felhasználási feltételekben:
"A Tanúsítók Jegyzéke csak az “ellenőrzött e-mail cím” és “van Titkos Kód” igazolással rendelkező felhasználók számára érhető el."
jelenleg nem így van

**Comment by Claymanus** [comment]
Ui-on implementálva, 
- E2E teszt kellene hozzá esetleg
- és jó lenne, ha a backend is csinálna jogosultságellenőrzést
ezekre veszek fel külön jegyet
