### ISSUE TITLE
add claymanus repo key to artifact repo

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#897]

**Comment by Claymanus** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3fJO6RMoRjK00or3J1tJxgoco839yjQ919HF6otTuTqbC1h7oo8m2+qH6KzqDeCUt+ApVx1gXD6Tk1/uMiWrDqzn55r3AukA/S/UUIXxdqS5W2JfOhWOf4iWMMaSdBvadFVCcyR2KcZG/wqKVAT+WFrXkTuwentw6TdCXWNmHITDt1DQI8SkOpG4fwMjGjoDHHjJUdEHCvheYNQHYbEiNUKWBqdpQspZEZIr77xCeRljKsI8Paq6Fy0L64yma/FHtrq9mEA4VIzf3diDL9GbTzFCbwYNG3u6W8f8t5JRkEVwHC6FBretIEqCG0BJzzQv0ow+TRWjZ0X3dDQQ+4Q/5 55809959edd7f2c0521c84d2
