### ISSUE TITLE
html code to check

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#904]
The diffs between the original and the generated html pages.
Please check them.
http://paste.ubuntu.com/23802873/
http://paste.ubuntu.com/23802874/
http://paste.ubuntu.com/23802876/
http://paste.ubuntu.com/23802877/

**Comment by magwas** [comment]
I need it for #889

**Comment by Claymanus** [comment]
fiókom.html 
![image](https://cloud.githubusercontent.com/assets/1410059/21961405/5482ea76-db09-11e6-9bc6-ac3439288f23.png)
miért lett aktív ez a menüpont?

**Comment by Claymanus** [comment]
fiókom.html
![image](https://cloud.githubusercontent.com/assets/1410059/21961458/5091f000-db0a-11e6-932d-7495ecef1c39.png)
ez miért változott?

**Comment by Claymanus** [comment]
about-us.html
![image](https://cloud.githubusercontent.com/assets/1410059/21961536/58036470-db0c-11e6-99a4-98b52e3090d8.png
Ide a statikus lapoknak megfelelő menu-item href kell, a fiokom.html-e lett iderakva. Ha ezt snipetesíteni akarjuk, akkor a js-nek kell beállítani a href-eket.

**Comment by Claymanus** [comment]
#945-ben a fellelt diszkrepanciák orvosolva
