### ISSUE TITLE
tanúsítási szabályzat kiegészítés

### ISSUE THREAD

**Issue by krosza** [edemo/PDOauth#920]
megbeszélés szerint

innen, az ötödik mellékletbe 
https://docs.google.com/document/d/1dOcXrOxI6hrcqmAP7Ft-aw1P_84cYsD29dWNQ4CsaTg/edit

a hatodikba pedig a tesztkérdéseket

**Comment by madcsaba** [comment]
nálam done

**Comment by krosza** [comment]
a főcímben nálam még a régi felsorolás van és a Faq után lemaradt a megállapodás rész legalábbis nemtalálom

**Comment by madcsaba** [comment]
done
