### ISSUE TITLE
felhasználási feltételek elfogadása regisztrációkor

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#96]
facebook uses this:
"
A Regisztráció gombra való kattintással elfogadod a Feltételeinket, és tudomásul veszed az Adatkezelési szabályzatban foglaltakat, beleértve a cookie-k használatáról szóló tájékoztatást is.
"

**Comment by magwas** [comment]
https://docs.google.com/document/d/1mSbcQ4kRAYPIv0VXNICDkhpW0AshSikHTCW4uUD1mxs/edit#
